import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createHash,randomUUID} from 'node:crypto';
const require=createRequire(import.meta.url),root=process.env.GST_TEST_BUILD;
const load=n=>require(`${root}/${n}.js`);
const {createHash:browserHash}=load('gst-hash');
const {prepareRspCartEntry}=load('rsp-cart-entry');
const {rspItemsForIssue}=load('rsp-issue-items');
const {mixedCartProjection}=load('mixed-cart-projection');
const {buildMixedGstFiscalDocument}=load('gst-core/mixed-gst-fiscal');
const {buildMixedCreditDocument}=load('gst-core/mixed-credit-fiscal');
const {buildRoundedFiscalDocument}=load('gst-core/payable-rounding-fiscal');
const {buildRoundedCreditDocument,planRoundedMixedCreditFromDocuments}=load('gst-core/payable-rounding-credit-fiscal');
const {normalizeRspProductProfile}=load('gst-core/rsp-profile-contract');
const {fiscalDocumentHash}=load('gst-core/fiscal-integrity');
const {assertCartTaxSnapshots,attachCatalogTaxSnapshot}=load('gst-core/gst-tax-cache');
const {documentView}=load('gst-document-view');
const {verifyDocument}=load('gst-document');
const {specialReturnPreview,verifiedReturnDocuments}=load('gst-return-preview');
const {documentHtml}=load('gst-print');
const shop=randomUUID(),saleId=randomUUID(),product=randomUUID(),lineId=randomUUID(),time='2026-10-08T00:00:00.000Z';
assert.equal(browserHash('sha256').update('বাংলা தமிழ் हिंदी ₹').digest('hex'),createHash('sha256').update('বাংলা தமிழ் हिंदी ₹').digest('hex'));
const profile=normalizeRspProductProfile({format:'samaan_rsp_product_profile_v1',version:randomUUID(),productId:product,rule:'cgst_rule_31d_2026',effectiveFrom:'2026-02-01T00:00:00+05:30',sourceReference:'SYNTHETIC',reviewed:true,goods:{hsn:'21069020',description:'pan_masala',reviewed:true,evidenceReference:'SYNTHETIC'},rates:{version:'QA',sourceReference:'SYNTHETIC',reviewed:true,cgst:20,sgst:20,utgst:0,igst:0}});
const snapshot={version:1,shopId:shop,productId:product,capturedAt:time,profiles:[{version:profile.version,recordedAt:'2026-09-01T00:00:00.000Z',effectiveAt:profile.effectiveFrom,state:'reviewed',profile}]};
const line={productId:product,name:'Synthetic package',unit:'piece',quantity:2,price:90,listPrice:100,discount:0,key:lineId};
const draft={area:'QA',packageId:'pack',prices:'120,130',increases:'140',evidence:'SYNTHETIC',reviewed:true};
const prepared=prepareRspCartEntry(line,snapshot,shop,draft,time);
assert.equal(prepared.calculation.statutory.tax,'80.00');assert.equal(prepared.calculation.payable,'260.00');
assert.throws(()=>prepareRspCartEntry({...line,quantity:0.5},snapshot,shop,draft,time));
assert.throws(()=>prepareRspCartEntry(line,snapshot,saleId,draft,time));
assert.throws(()=>prepareRspCartEntry(line,snapshot,shop,{...draft,reviewed:false},time));
assert.throws(()=>rspItemsForIssue([{...prepared.line,quantity:3}],time));
const settings={version:randomUUID(),registration:'regular',gstin:'29AAAGM0289C1ZF',legalName:'Synthetic Shop',address:'Bengaluru',stateCode:'29',priceMode:'exclusive',effectiveFrom:'2026-01-01',reviewed:true,eInvoiceRequired:false};
const context={settings,priceMode:'exclusive',placeOfSupply:'29',issuedAt:time,documentRenderVersion:'gst_bill_v2',allocation:{id:randomUUID(),index:1,number:'26-1-001',financialYear:'2026-27',deviceEpoch:randomUUID()}};
const projection=mixedCartProjection([{...prepared.line,key:lineId}],context,0);
assert.equal(projection.payable,'260.00');assert.throws(()=>mixedCartProjection([{...prepared.line,key:lineId}],context,10));
const original=buildMixedGstFiscalDocument({shopId:shop,saleId},context,[{kind:'rsp',lineId,profile,transaction:{productId:product,valuation:prepared.line.rsp.valuation,rounding:prepared.line.rsp.rounding,grossSaleValue:'200.00',discount:'20.00'}}]);
original.payload.items=[{lineId,productId:product,name:line.name,unit:line.unit,categorySnapshot:'General'}];original.hash=fiscalDocumentHash(original);
const saved=doc=>({...doc,id:randomUUID(),integrity:'verified'});
const verified=saved(original);await verifyDocument(verified,shop,saleId);
const view=documentView(verified);assert.equal(view.total,260);assert.equal(view.tax,80);assert.equal(view.net,180);assert.equal(view.lines[0].quantity,2);
const policy={format:'payable_rounding_policy_v1',version:randomUUID(),shopId:shop,mode:'nearest_rupee',effectiveFrom:'2026-01-01T00:00:00.000Z',effectiveUntil:null,reviewed:true,evidenceReference:'SYNTHETIC'};
const rounded=buildRoundedFiscalDocument(original,policy);await verifyDocument(saved(rounded),shop,saleId);assert.equal(documentView(rounded).total,260);
const rows=[{lineId,returnedQuantity:0}],requestId=randomUUID(),selections=[{lineId,returning:1}];
const plan=planRoundedMixedCreditFromDocuments(rounded,[],rows,selections,{requestId,initialUnpaidCredit:'0.00',currentUnpaidCredit:'0.00'});
assert.equal(plan.rounding.settlement.payable,'130.00');
const taxCredit=buildMixedCreditDocument(original,{number:'CN26-1',issuedAt:'2026-10-08T01:00:00.000Z',returnId:randomUUID(),requestId,createdBy:'synthetic-owner'},plan.selections);
const credit=buildRoundedCreditDocument(rounded,taxCredit,plan.request);await verifyDocument(saved(credit),shop,saleId);assert.equal(documentView(credit).total,130);
const confirmedDocuments=await verifiedReturnDocuments(shop,saleId,[saved(rounded),saved(credit)]);
const sale={id:saleId,shopId:shop,gstIntegrity:'verified',mixedGstSnapshot:original.payload,roundingEvidence:rounded.payload.rounding,creditTotal:0,items:[{id:lineId,quantity:2,returnedQuantity:1}]};
assert.equal(specialReturnPreview(sale,confirmedDocuments,{[lineId]:'1'},randomUUID(),'0.00').total,130);
assert.throws(()=>specialReturnPreview(sale,[saved(rounded)],{[lineId]:'1'},randomUUID(),'0.00'));
assert.throws(()=>specialReturnPreview(sale,confirmedDocuments,{[lineId]:'2'},randomUUID(),'0.00'));
const bad=structuredClone(rounded);bad.payload.finalPayable='261.00';bad.hash=fiscalDocumentHash(bad);await assert.rejects(()=>verifyDocument(saved(bad),shop,saleId));
const unknown=structuredClone(original);unknown.payload.format='unknown_fiscal';unknown.hash=fiscalDocumentHash(unknown);await assert.rejects(()=>verifyDocument(saved(unknown),shop,saleId));
await assert.rejects(()=>verifiedReturnDocuments(randomUUID(),saleId,[saved(original)]));
const tax={version:randomUUID(),category:'taxable',codeType:'hsn',code:'1006',rate:5,reviewed:true};
const timeline={version:1,shopId:shop,capturedAt:time,products:[{productId:product,profiles:[{version:tax.version,recordedAt:time,effectiveAt:time,state:'reviewed',config:tax}]}]};
const attached=attachCatalogTaxSnapshot([{product:{id:product}}],timeline,shop)[0].product;
assert.doesNotThrow(()=>assertCartTaxSnapshots({gstTaxSnapshotsRequired:true,lines:[{productId:product,...attached}]},shop,time));
assert.throws(()=>assertCartTaxSnapshots({gstTaxSnapshotsRequired:true,lines:[{productId:product,...attached,gstConfig:{...tax,rate:12}}]},shop,time));
assert.throws(()=>attachCatalogTaxSnapshot([{product:{id:product}}],{...timeline,products:[]},shop));
const html=documentHtml({outerHTML:'<article>ONLY SELECTED INVOICE</article>'},'<unsafe title>');assert.match(html,/ONLY SELECTED INVOICE/);assert.ok(!html.includes('<unsafe title>'));assert.match(html,/table-header-group/);
console.log('Web parity tests passed: browser hashes, RSP package review, mixed invoice rendering, rounded credits, cumulative returns, scope/tamper rejection, tax timelines and selected-document print output.');

const legacyLine={net:450,tax:0,cgst:0,sgst:0,utgst:0,igst:0,total:450,taxable:450,gross:450,discount:0,billDiscount:0,category:'taxable',codeType:'hsn',code:'1006',rate:0,profileVersion:randomUUID()};
const legacyCredit={type:'credit_note',originalNumber:'26-3-001',payload:{original:{invoiceNumber:'26-3-001',context:original.payload.context},items:[{name:'QA book',unit:'piece',quantity:1,tax:legacyLine}],net:450,tax:0,total:450,settlement:{creditReduction:'0.00',moneyRefund:'450.00',total:'450.00'}}};
assert.equal(documentView(legacyCredit).total,450);assert.equal(documentView(legacyCredit).moneyRefund,450);
assert.throws(()=>documentView({...legacyCredit,payload:{...legacyCredit.payload,total:449}}),/inconsistent/);
assert.throws(()=>documentView({...legacyCredit,originalNumber:'wrong'}),/inconsistent/);

// Value-only service credits retain totals under payload.totals, not return payload.net/tax/total.
const serviceTax={...legacyLine,codeType:'sac',code:'998719',rate:18,gross:20,net:20,taxable:20,tax:3.6,cgst:1.8,sgst:1.8,total:23.6};
const serviceTotals={version:1,subtotal:20,discount:0,billDiscount:0,net:20,taxable:20,tax:3.6,cgst:1.8,sgst:1.8,utgst:0,igst:0,total:23.6,lines:[serviceTax]};
const valueCredit={...legacyCredit,payload:{version:1,type:'credit_note',stockEffect:'none',taxAdjustmentStatus:'review_required',original:legacyCredit.payload.original,context:legacyCredit.payload.original.context,reason:'Synthetic service value correction',items:[{name:'QA service',unit:'piece',quantity:1,tax:serviceTax}],totals:serviceTotals,settlement:{creditReduction:'0.00',moneyRefund:'23.60',total:'23.60'}}};
assert.equal(documentView(valueCredit).total,23.6);
assert.equal(documentView(valueCredit).tax,3.6);
assert.equal(documentView(valueCredit).moneyRefund,23.6);
assert.throws(()=>documentView({...valueCredit,payload:{...valueCredit.payload,totals:{...serviceTotals,total:23.61}}}),/inconsistent/);
assert.throws(()=>documentView({...valueCredit,payload:{...valueCredit.payload,totals:{...serviceTotals,lines:[legacyLine]}}}),/inconsistent/);
assert.throws(()=>documentView({...valueCredit,payload:{...valueCredit.payload,settlement:{creditReduction:'0.00',moneyRefund:'23.61',total:'23.61'}}}),/inconsistent/);
