import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {premiumAt,retainEntitlement}=require(process.env.GST_TEST_BUILD+'/offline-premium.js');
const now=Date.parse('2026-10-09T12:00:00Z');
const active={status:'active',plan:'monthly',isPremium:true,currentPeriodEnd:new Date(now+1000).toISOString(),trialEnd:null,temporaryPremium:false,subscriptionId:'private-id',invoices:[{invoiceUrl:'private-url'}]};
assert.equal(premiumAt(active,now),true);
assert.equal(premiumAt(active,now+1000),false);
assert.equal(premiumAt({...active,currentPeriodEnd:null},now),false);
assert.equal(premiumAt({...active,status:'trialing',trialEnd:new Date(now+500).toISOString()},now+500),false);
assert.equal(premiumAt({...active,isPremium:false,temporaryPremium:true},now),false);
assert.equal(premiumAt({...active,temporaryPremium:true},now+2000),true);
const retained=retainEntitlement({...active,temporaryPremium:true},now);
assert.equal(premiumAt(retained,now+7*86400000-1),true);
assert.equal(premiumAt(retained,now+7*86400000),false);
assert.equal('subscriptionId' in retained,false);
assert.equal('invoices' in retained,false);
assert.equal(premiumAt(retainEntitlement({...active,status:'canceled',isPremium:false},now),now),false);
console.log('Premium evidence: active/trial exact expiry, temporary server grant, cache expiry and private billing redaction passed.');
