import type { Locale } from '../i18n';

export type SubscriptionStrings = {
  brand: { tagline: string };
  nav: { features: string; ai: string; pricing: string; account: string; download: string };
  footer: {
    product: string;
    company: string;
    support: string;
    features: string;
    ai: string;
    pricing: string;
    about: string;
    blog: string;
    careers: string;
    contact: string;
    account: string;
    refund: string;
    privacy: string;
    terms: string;
    copyright: string;
  };
  plans: {
    monthlyLabel: string;
    annualLabel: string;
    monthlyDescription: string;
    annualDescription: string;
  };
  pricing: {
    heroTitle: string;
    heroLead: string;
    ctaSubscribe: string;
    ctaOpenInApp: string;
    planSelectorLabel: string;
    billingIntervalLabel: string;
    selectedPlan: string;
    annualSavings: string;
    monthlyFlexible: string;
    subscribeWithAmount: (amount: string) => string;
    refundWindow: string;
    razorpaySecure: string;
    gstInvoice: string;
    comparisonHeading: string;
    freeHeading: string;
    premiumHeading: string;
    freeFeatures: string[];
    premiumFeatures: string[];
    secureBillingHeading: string;
    trustStrip: string[];
    faqHeading: string;
    faq: Array<{ q: string; a: string }>;
  };
  account: {
    loadingSignIn: string;
    loadingAccount: string;
    signedOutHeading: string;
    signedOutLead: string;
    heading: string;
    leadWithEmail: (email: string) => string;
    accountFallback: string;
    linkedShops: string;
    loadingShops: string;
    noShops: string;
    shopRoleFallback: string;
    statusLoading: string;
    statusActive: (interval: string) => string;
    statusTrialEnds: (date: string) => string;
    statusPastDue: string;
    statusCanceled: string;
    statusLegacyFree: string;
    statusNone: string;
    dateUnavailable: string;
    selectShop: string;
    renewsOn: (date: string) => string;
    chooseIntervalPrompt: string;
    currentPlan: (label: string) => string;
    switchToAnnual: (amount: string) => string;
    switchToMonthly: (amount: string) => string;
    updatePaymentMethod: string;
    cancelSubscription: string;
    subscribeWithAmount: (amount: string) => string;
    paymentHistory: string;
    invoiceDate: string;
    invoiceAmount: string;
    invoiceStatus: string;
    invoiceColumn: string;
    invoiceDownload: string;
    invoicePending: string;
    invoicePaid: string;
    noInvoices: string;
    backToPricing: string;
    errorRazorpayNotLoaded: string;
    errorCheckoutMissingId: string;
    errorLoadShops: string;
    errorLoadEntitlement: string;
    errorStartCheckout: string;
    errorSwitchPlan: string;
    errorPaymentMethod: string;
    errorCancel: string;
  };
  contact: {
    heading: string;
    lead: string;
    emailHeading: string;
    developerHeading: string;
    responseHeading: string;
    responseBody: string;
    businessHeading: string;
    businessBody: string;
  };
};

const en: SubscriptionStrings = {
  brand: { tagline: 'Voice-first AI inventory management, built for the heart of Indian retail.' },
  nav: { features: 'Features', ai: 'AI Intelligence', pricing: 'Pricing', account: 'Account', download: 'Download App' },
  footer: {
    product: 'Product',
    company: 'Company',
    support: 'Support',
    features: 'Features',
    ai: 'AI Intelligence',
    pricing: 'Pricing',
    about: 'About',
    blog: 'Blog',
    careers: 'Careers',
    contact: 'Contact',
    account: 'Account',
    refund: 'Refund Policy',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    copyright: '© Samaan-Bol. Voice-first inventory for Indian retail.',
  },
  plans: {
    monthlyLabel: 'Monthly',
    annualLabel: 'Annual',
    monthlyDescription: 'Premium — Monthly',
    annualDescription: 'Premium — Annual',
  },
  pricing: {
    heroTitle: 'Premium for ₹499/month or ₹3,999/year',
    heroLead:
      'Subscribe on web for secure Razorpay UPI Autopay. Built for iOS users who manage billing outside the app, and useful for every shop owner who wants invoices, cancellations, and account control in one place.',
    ctaSubscribe: 'Subscribe — Sign in',
    ctaOpenInApp: 'Open in app',
    planSelectorLabel: 'Plan selector',
    billingIntervalLabel: 'Billing interval',
    selectedPlan: 'Selected plan',
    annualSavings: 'Save about 33%. Effective price is about ₹333/month.',
    monthlyFlexible: 'Flexible monthly billing. Cancel before the next billing cycle.',
    subscribeWithAmount: (amount) => `Subscribe — ${amount}`,
    refundWindow: '7-day refund window from first charge',
    razorpaySecure: 'Secure payments by Razorpay',
    gstInvoice: 'GST invoice support through Razorpay',
    comparisonHeading: 'Choose the inventory system that matches your shop',
    freeHeading: 'Free',
    premiumHeading: 'Premium',
    freeFeatures: [
      'Basic product CRUD',
      'Single shop',
      'Manual stock entry',
      'Barcode scan',
      'Team invites',
      'Essential audit trail',
    ],
    premiumFeatures: [
      'Voice AI in Hindi, English, and regional Indian languages',
      'AI stock predictions and expiry alerts',
      'Advanced analytics and full inventory history',
      'Multi-shop support for growing retailers',
      'AI buy-list suggestions before stockouts',
      'Team collaboration with audit trails',
    ],
    secureBillingHeading: 'Secure billing for Indian shops',
    trustStrip: ['Razorpay hosted checkout', 'UPI Autopay supported', 'Cancel anytime', '7-day refund window'],
    faqHeading: 'Questions before you subscribe',
    faq: [
      {
        q: 'What is UPI Autopay?',
        a: 'UPI Autopay lets you approve a recurring mandate once, then Razorpay collects future subscription payments automatically under RBI rules.',
      },
      {
        q: 'Can I cancel anytime?',
        a: 'Yes. Cancellation stops future renewals. Premium access continues until the end of the paid period.',
      },
      {
        q: 'Will I get a GST invoice?',
        a: 'Invoices are issued through Razorpay when billing information is available for the subscription.',
      },
      {
        q: 'Is my payment information safe?',
        a: 'Razorpay handles sensitive payment details. Samaan-Bol receives only payment and subscription metadata needed to manage access.',
      },
    ],
  },
  account: {
    loadingSignIn: 'Loading sign-in status...',
    loadingAccount: 'Loading account...',
    signedOutHeading: 'Sign in to manage your subscription',
    signedOutLead:
      'Use the same Clerk account email you use in the Samaan-Bol app. iOS users subscribe and manage billing here on the web.',
    heading: 'Account',
    leadWithEmail: (email) =>
      `Manage shop subscriptions, Razorpay checkout, invoices, cancellations, and account access for ${email}.`,
    accountFallback: 'your Samaan-Bol account',
    linkedShops: 'Linked shops',
    loadingShops: 'Loading shops...',
    noShops: 'No shops were returned by the subscription API.',
    shopRoleFallback: 'Shop access',
    statusLoading: 'Loading',
    statusActive: (interval) => `Premium — ${interval}`,
    statusTrialEnds: (date) => `Trial — ends ${date}`,
    statusPastDue: 'Payment failed',
    statusCanceled: 'Canceled',
    statusLegacyFree: 'Legacy free',
    statusNone: 'No active subscription',
    dateUnavailable: 'Not available',
    selectShop: 'Select a shop',
    renewsOn: (date) => `Renews or changes on ${date}`,
    chooseIntervalPrompt: 'Choose a billing interval and start Razorpay checkout for this shop.',
    currentPlan: (label) =>
      `Your current plan is ${label}. Switching plans or updating your payment method requires authorizing a new UPI Autopay mandate on Razorpay.`,
    switchToAnnual: (amount) => `Switch to Annual — ${amount}`,
    switchToMonthly: (amount) => `Switch to Monthly — ${amount}`,
    updatePaymentMethod: 'Update payment method',
    cancelSubscription: 'Cancel subscription',
    subscribeWithAmount: (amount) => `Subscribe — ${amount}`,
    paymentHistory: 'Payment history',
    invoiceDate: 'Date',
    invoiceAmount: 'Amount',
    invoiceStatus: 'Status',
    invoiceColumn: 'Invoice',
    invoiceDownload: 'Download',
    invoicePending: 'Pending',
    invoicePaid: 'Paid',
    noInvoices: 'No Razorpay invoices are available yet.',
    backToPricing: 'Back to pricing',
    errorRazorpayNotLoaded: 'Razorpay Checkout has not loaded yet. Refresh the page and try again.',
    errorCheckoutMissingId: 'Checkout response missing subscription_id or key_id.',
    errorLoadShops: 'Unable to load shops.',
    errorLoadEntitlement: 'Unable to load subscription status.',
    errorStartCheckout: 'Unable to start checkout.',
    errorSwitchPlan: 'Unable to switch plan.',
    errorPaymentMethod: 'Unable to update payment method.',
    errorCancel: 'Unable to cancel subscription.',
  },
  contact: {
    heading: 'Contact Support',
    lead: 'For subscription, invoice, account, refund, or app support, contact the Samaan-Bol team by email.',
    emailHeading: 'Email',
    developerHeading: 'Developer contact',
    responseHeading: 'Response time',
    responseBody:
      'We aim to respond within 2 business days. Refund and billing requests may require Razorpay payment identifiers for verification.',
    businessHeading: 'Business address',
    businessBody:
      'Samaan-Bol, India. Registered business address and GSTIN will be shown here once confirmed for Razorpay/GST invoice compliance.',
  },
};

const hi: SubscriptionStrings = {
  brand: { tagline: 'भारतीय रिटेल के दिल के लिए बनाया गया, वॉयस-फ़र्स्ट AI इन्वेंट्री प्रबंधन।' },
  nav: { features: 'फ़ीचर्स', ai: 'AI इंटेलिजेंस', pricing: 'मूल्य', account: 'खाता', download: 'ऐप डाउनलोड करें' },
  footer: {
    product: 'प्रोडक्ट',
    company: 'कंपनी',
    support: 'सहायता',
    features: 'फ़ीचर्स',
    ai: 'AI इंटेलिजेंस',
    pricing: 'मूल्य',
    about: 'हमारे बारे में',
    blog: 'ब्लॉग',
    careers: 'करियर',
    contact: 'संपर्क',
    account: 'खाता',
    refund: 'रिफ़ंड नीति',
    privacy: 'गोपनीयता नीति',
    terms: 'सेवा की शर्तें',
    copyright: '© Samaan-Bol. भारतीय रिटेल के लिए वॉयस-फ़र्स्ट इन्वेंट्री।',
  },
  plans: {
    monthlyLabel: 'मासिक',
    annualLabel: 'वार्षिक',
    monthlyDescription: 'प्रीमियम — मासिक',
    annualDescription: 'प्रीमियम — वार्षिक',
  },
  pricing: {
    heroTitle: 'प्रीमियम ₹499/महीना या ₹3,999/साल पर',
    heroLead:
      'सुरक्षित Razorpay UPI ऑटोपे के लिए वेब पर सब्सक्राइब करें। iOS यूज़र्स के लिए बनाया गया जो ऐप के बाहर बिलिंग प्रबंधित करते हैं, और हर दुकानदार के लिए उपयोगी जो इनवॉइस, कैंसिलेशन और अकाउंट कंट्रोल एक जगह चाहता है।',
    ctaSubscribe: 'सब्सक्राइब करें — साइन इन',
    ctaOpenInApp: 'ऐप में खोलें',
    planSelectorLabel: 'प्लान चुनें',
    billingIntervalLabel: 'बिलिंग अंतराल',
    selectedPlan: 'चुना गया प्लान',
    annualSavings: 'लगभग 33% बचाएँ। प्रभावी मूल्य लगभग ₹333/महीना।',
    monthlyFlexible: 'लचीली मासिक बिलिंग। अगले बिलिंग चक्र से पहले रद्द करें।',
    subscribeWithAmount: (amount) => `सब्सक्राइब करें — ${amount}`,
    refundWindow: 'पहले शुल्क से 7-दिन की रिफ़ंड विंडो',
    razorpaySecure: 'Razorpay द्वारा सुरक्षित भुगतान',
    gstInvoice: 'Razorpay के माध्यम से GST इनवॉइस सपोर्ट',
    comparisonHeading: 'अपनी दुकान से मेल खाता इन्वेंट्री सिस्टम चुनें',
    freeHeading: 'फ़्री',
    premiumHeading: 'प्रीमियम',
    freeFeatures: [
      'बेसिक प्रोडक्ट प्रबंधन',
      'एक दुकान',
      'मैन्युअल स्टॉक एंट्री',
      'बारकोड स्कैन',
      'टीम निमंत्रण',
      'आवश्यक ऑडिट ट्रेल',
    ],
    premiumFeatures: [
      'हिंदी, अंग्रेज़ी और क्षेत्रीय भारतीय भाषाओं में वॉयस AI',
      'AI स्टॉक भविष्यवाणी और एक्सपायरी अलर्ट',
      'उन्नत एनालिटिक्स और पूर्ण इन्वेंट्री इतिहास',
      'बढ़ते रिटेलर्स के लिए मल्टी-शॉप सपोर्ट',
      'स्टॉकआउट से पहले AI बाय-लिस्ट सुझाव',
      'ऑडिट ट्रेल के साथ टीम सहयोग',
    ],
    secureBillingHeading: 'भारतीय दुकानों के लिए सुरक्षित बिलिंग',
    trustStrip: ['Razorpay होस्टेड चेकआउट', 'UPI ऑटोपे समर्थित', 'कभी भी रद्द करें', '7-दिन रिफ़ंड विंडो'],
    faqHeading: 'सब्सक्राइब करने से पहले के सवाल',
    faq: [
      {
        q: 'UPI ऑटोपे क्या है?',
        a: 'UPI ऑटोपे आपको एक बार आवर्ती मैंडेट स्वीकृत करने देता है, फिर Razorpay भविष्य के सब्सक्रिप्शन भुगतान RBI नियमों के तहत स्वचालित रूप से लेता है।',
      },
      {
        q: 'क्या मैं कभी भी रद्द कर सकता हूँ?',
        a: 'हाँ। रद्द करने से भविष्य के नवीनीकरण रुक जाते हैं। प्रीमियम एक्सेस भुगतान अवधि के अंत तक जारी रहती है।',
      },
      {
        q: 'क्या मुझे GST इनवॉइस मिलेगा?',
        a: 'जब सब्सक्रिप्शन के लिए बिलिंग जानकारी उपलब्ध होती है, Razorpay के माध्यम से इनवॉइस जारी किए जाते हैं।',
      },
      {
        q: 'क्या मेरी भुगतान जानकारी सुरक्षित है?',
        a: 'Razorpay संवेदनशील भुगतान विवरण संभालता है। Samaan-Bol को केवल वही भुगतान और सब्सक्रिप्शन मेटाडेटा मिलता है जो एक्सेस प्रबंधन के लिए ज़रूरी है।',
      },
    ],
  },
  account: {
    loadingSignIn: 'साइन-इन स्थिति लोड हो रही है...',
    loadingAccount: 'खाता लोड हो रहा है...',
    signedOutHeading: 'अपनी सदस्यता प्रबंधित करने के लिए साइन इन करें',
    signedOutLead:
      'वही Clerk अकाउंट ईमेल उपयोग करें जो आप Samaan-Bol ऐप में करते हैं। iOS यूज़र्स यहाँ वेब पर सब्सक्राइब और बिलिंग प्रबंधित करते हैं।',
    heading: 'खाता',
    leadWithEmail: (email) =>
      `${email} के लिए दुकान सब्सक्रिप्शन, Razorpay चेकआउट, इनवॉइस, कैंसिलेशन और अकाउंट एक्सेस प्रबंधित करें।`,
    accountFallback: 'आपका Samaan-Bol खाता',
    linkedShops: 'लिंक की गई दुकानें',
    loadingShops: 'दुकानें लोड हो रही हैं...',
    noShops: 'सब्सक्रिप्शन API ने कोई दुकान नहीं लौटाई।',
    shopRoleFallback: 'दुकान एक्सेस',
    statusLoading: 'लोड हो रहा है',
    statusActive: (interval) => `प्रीमियम — ${interval}`,
    statusTrialEnds: (date) => `ट्रायल — ${date} को समाप्त`,
    statusPastDue: 'भुगतान विफल',
    statusCanceled: 'रद्द',
    statusLegacyFree: 'लीगेसी फ़्री',
    statusNone: 'कोई सक्रिय सदस्यता नहीं',
    dateUnavailable: 'उपलब्ध नहीं',
    selectShop: 'एक दुकान चुनें',
    renewsOn: (date) => `${date} को नवीनीकरण या परिवर्तन`,
    chooseIntervalPrompt: 'एक बिलिंग अंतराल चुनें और इस दुकान के लिए Razorpay चेकआउट शुरू करें।',
    currentPlan: (label) =>
      `आपका वर्तमान प्लान ${label} है। प्लान बदलने या भुगतान विधि अपडेट करने के लिए Razorpay पर नया UPI ऑटोपे मैंडेट अधिकृत करना आवश्यक है।`,
    switchToAnnual: (amount) => `वार्षिक पर स्विच करें — ${amount}`,
    switchToMonthly: (amount) => `मासिक पर स्विच करें — ${amount}`,
    updatePaymentMethod: 'भुगतान विधि अपडेट करें',
    cancelSubscription: 'सदस्यता रद्द करें',
    subscribeWithAmount: (amount) => `सब्सक्राइब करें — ${amount}`,
    paymentHistory: 'भुगतान इतिहास',
    invoiceDate: 'तारीख़',
    invoiceAmount: 'राशि',
    invoiceStatus: 'स्थिति',
    invoiceColumn: 'इनवॉइस',
    invoiceDownload: 'डाउनलोड',
    invoicePending: 'लंबित',
    invoicePaid: 'भुगतान',
    noInvoices: 'अभी तक कोई Razorpay इनवॉइस उपलब्ध नहीं है।',
    backToPricing: 'मूल्य पर वापस',
    errorRazorpayNotLoaded: 'Razorpay चेकआउट अभी लोड नहीं हुआ है। पेज रिफ़्रेश करें और फिर कोशिश करें।',
    errorCheckoutMissingId: 'चेकआउट प्रतिक्रिया में subscription_id या key_id गायब है।',
    errorLoadShops: 'दुकानें लोड करने में असमर्थ।',
    errorLoadEntitlement: 'सदस्यता स्थिति लोड करने में असमर्थ।',
    errorStartCheckout: 'चेकआउट शुरू करने में असमर्थ।',
    errorSwitchPlan: 'प्लान बदलने में असमर्थ।',
    errorPaymentMethod: 'भुगतान विधि अपडेट करने में असमर्थ।',
    errorCancel: 'सदस्यता रद्द करने में असमर्थ।',
  },
  contact: {
    heading: 'सहायता संपर्क',
    lead: 'सब्सक्रिप्शन, इनवॉइस, अकाउंट, रिफ़ंड या ऐप सहायता के लिए, Samaan-Bol टीम से ईमेल द्वारा संपर्क करें।',
    emailHeading: 'ईमेल',
    developerHeading: 'डेवलपर संपर्क',
    responseHeading: 'प्रतिक्रिया समय',
    responseBody:
      'हम 2 कार्य दिवसों के भीतर प्रतिक्रिया देने का लक्ष्य रखते हैं। रिफ़ंड और बिलिंग अनुरोधों के लिए सत्यापन हेतु Razorpay भुगतान पहचानकर्ताओं की आवश्यकता हो सकती है।',
    businessHeading: 'व्यापारिक पता',
    businessBody:
      'Samaan-Bol, भारत। Razorpay/GST इनवॉइस अनुपालन के लिए पुष्टि होने पर पंजीकृत व्यापारिक पता और GSTIN यहाँ दिखाया जाएगा।',
  },
};

const bn: SubscriptionStrings = {
  brand: { tagline: 'ভারতীয় রিটেলের হৃদয়ের জন্য তৈরি, ভয়েস-ফার্স্ট AI ইনভেন্টরি ব্যবস্থাপনা।' },
  nav: { features: 'ফিচার', ai: 'AI ইন্টেলিজেন্স', pricing: 'মূল্য', account: 'অ্যাকাউন্ট', download: 'অ্যাপ ডাউনলোড করুন' },
  footer: {
    product: 'প্রোডাক্ট',
    company: 'কোম্পানি',
    support: 'সহায়তা',
    features: 'ফিচার',
    ai: 'AI ইন্টেলিজেন্স',
    pricing: 'মূল্য',
    about: 'আমাদের সম্পর্কে',
    blog: 'ব্লগ',
    careers: 'কেরিয়ার',
    contact: 'যোগাযোগ',
    account: 'অ্যাকাউন্ট',
    refund: 'রিফান্ড নীতি',
    privacy: 'গোপনীয়তা নীতি',
    terms: 'পরিষেবার শর্তাবলী',
    copyright: '© Samaan-Bol. ভারতীয় রিটেলের জন্য ভয়েস-ফার্স্ট ইনভেন্টরি।',
  },
  plans: { monthlyLabel: 'মাসিক', annualLabel: 'বার্ষিক', monthlyDescription: 'প্রিমিয়াম — মাসিক', annualDescription: 'প্রিমিয়াম — বার্ষিক' },
  pricing: {
    heroTitle: 'প্রিমিয়াম ₹499/মাস বা ₹3,999/বছর',
    heroLead:
      'নিরাপদ Razorpay UPI অটোপে-এর জন্য ওয়েবে সাবস্ক্রাইব করুন। iOS ব্যবহারকারীদের জন্য তৈরি যারা অ্যাপের বাইরে বিলিং পরিচালনা করেন, এবং প্রতিটি দোকানদারের জন্য উপযোগী যিনি ইনভয়েস, বাতিলকরণ ও অ্যাকাউন্ট নিয়ন্ত্রণ এক জায়গায় চান।',
    ctaSubscribe: 'সাবস্ক্রাইব — সাইন ইন',
    ctaOpenInApp: 'অ্যাপে খুলুন',
    planSelectorLabel: 'প্ল্যান নির্বাচন',
    billingIntervalLabel: 'বিলিং বিরতি',
    selectedPlan: 'নির্বাচিত প্ল্যান',
    annualSavings: 'প্রায় ৩৩% সাশ্রয় করুন। কার্যকর মূল্য প্রায় ₹333/মাস।',
    monthlyFlexible: 'নমনীয় মাসিক বিলিং। পরবর্তী বিলিং চক্রের আগে বাতিল করুন।',
    subscribeWithAmount: (amount) => `সাবস্ক্রাইব — ${amount}`,
    refundWindow: 'প্রথম চার্জ থেকে ৭-দিনের রিফান্ড উইন্ডো',
    razorpaySecure: 'Razorpay-এর মাধ্যমে নিরাপদ পেমেন্ট',
    gstInvoice: 'Razorpay-এর মাধ্যমে GST ইনভয়েস সহায়তা',
    comparisonHeading: 'আপনার দোকানের সাথে মানানসই ইনভেন্টরি সিস্টেম বেছে নিন',
    freeHeading: 'ফ্রি',
    premiumHeading: 'প্রিমিয়াম',
    freeFeatures: ['বেসিক প্রোডাক্ট ব্যবস্থাপনা', 'একটি দোকান', 'ম্যানুয়াল স্টক এন্ট্রি', 'বারকোড স্ক্যান', 'টিম আমন্ত্রণ', 'প্রয়োজনীয় অডিট ট্রেইল'],
    premiumFeatures: [
      'হিন্দি, ইংরেজি ও আঞ্চলিক ভারতীয় ভাষায় ভয়েস AI',
      'AI স্টক পূর্বাভাস ও মেয়াদ শেষের সতর্কতা',
      'উন্নত অ্যানালিটিক্স ও সম্পূর্ণ ইনভেন্টরি ইতিহাস',
      'বর্ধনশীল রিটেলারদের জন্য মাল্টি-শপ সাপোর্ট',
      'স্টক শেষ হওয়ার আগে AI বাই-লিস্ট পরামর্শ',
      'অডিট ট্রেইল সহ টিম সহযোগিতা',
    ],
    secureBillingHeading: 'ভারতীয় দোকানগুলির জন্য নিরাপদ বিলিং',
    trustStrip: ['Razorpay হোস্টেড চেকআউট', 'UPI অটোপে সমর্থিত', 'যেকোনো সময় বাতিল করুন', '৭-দিনের রিফান্ড উইন্ডো'],
    faqHeading: 'সাবস্ক্রাইব করার আগে প্রশ্ন',
    faq: [
      { q: 'UPI অটোপে কী?', a: 'UPI অটোপে আপনাকে একবার একটি রিকারিং ম্যান্ডেট অনুমোদন করতে দেয়, তারপর Razorpay RBI নিয়মের অধীনে স্বয়ংক্রিয়ভাবে ভবিষ্যত সাবস্ক্রিপশন পেমেন্ট সংগ্রহ করে।' },
      { q: 'আমি কি যেকোনো সময় বাতিল করতে পারি?', a: 'হ্যাঁ। বাতিলকরণ ভবিষ্যত নবায়ন বন্ধ করে। প্রিমিয়াম অ্যাক্সেস পরিশোধিত সময়সীমার শেষ পর্যন্ত চলতে থাকে।' },
      { q: 'আমি কি GST ইনভয়েস পাব?', a: 'সাবস্ক্রিপশনের জন্য বিলিং তথ্য উপলব্ধ থাকলে Razorpay-এর মাধ্যমে ইনভয়েস ইস্যু করা হয়।' },
      { q: 'আমার পেমেন্ট তথ্য কি নিরাপদ?', a: 'Razorpay সংবেদনশীল পেমেন্ট বিবরণ পরিচালনা করে। Samaan-Bol শুধু অ্যাক্সেস পরিচালনার জন্য প্রয়োজনীয় পেমেন্ট ও সাবস্ক্রিপশন মেটাডেটা পায়।' },
    ],
  },
  account: {
    loadingSignIn: 'সাইন-ইন স্থিতি লোড হচ্ছে...',
    loadingAccount: 'অ্যাকাউন্ট লোড হচ্ছে...',
    signedOutHeading: 'আপনার সাবস্ক্রিপশন পরিচালনা করতে সাইন ইন করুন',
    signedOutLead: 'Samaan-Bol অ্যাপে আপনি যে Clerk অ্যাকাউন্ট ইমেল ব্যবহার করেন তাই ব্যবহার করুন। iOS ব্যবহারকারীরা এখানে ওয়েবে সাবস্ক্রাইব ও বিলিং পরিচালনা করেন।',
    heading: 'অ্যাকাউন্ট',
    leadWithEmail: (email) => `${email}-এর জন্য দোকান সাবস্ক্রিপশন, Razorpay চেকআউট, ইনভয়েস, বাতিলকরণ ও অ্যাকাউন্ট অ্যাক্সেস পরিচালনা করুন।`,
    accountFallback: 'আপনার Samaan-Bol অ্যাকাউন্ট',
    linkedShops: 'লিঙ্ক করা দোকান',
    loadingShops: 'দোকান লোড হচ্ছে...',
    noShops: 'সাবস্ক্রিপশন API কোনো দোকান ফেরত দেয়নি।',
    shopRoleFallback: 'দোকান অ্যাক্সেস',
    statusLoading: 'লোড হচ্ছে',
    statusActive: (interval) => `প্রিমিয়াম — ${interval}`,
    statusTrialEnds: (date) => `ট্রায়াল — ${date}-এ শেষ`,
    statusPastDue: 'পেমেন্ট ব্যর্থ',
    statusCanceled: 'বাতিল',
    statusLegacyFree: 'লিগ্যাসি ফ্রি',
    statusNone: 'কোনো সক্রিয় সাবস্ক্রিপশন নেই',
    dateUnavailable: 'উপলব্ধ নয়',
    selectShop: 'একটি দোকান নির্বাচন করুন',
    renewsOn: (date) => `${date}-এ নবায়ন বা পরিবর্তন`,
    chooseIntervalPrompt: 'একটি বিলিং বিরতি বেছে নিন এবং এই দোকানের জন্য Razorpay চেকআউট শুরু করুন।',
    currentPlan: (label) => `আপনার বর্তমান প্ল্যান ${label}। প্ল্যান পরিবর্তন বা পেমেন্ট পদ্ধতি আপডেট করতে Razorpay-এ একটি নতুন UPI অটোপে ম্যান্ডেট অনুমোদন করা প্রয়োজন।`,
    switchToAnnual: (amount) => `বার্ষিকে স্যুইচ করুন — ${amount}`,
    switchToMonthly: (amount) => `মাসিকে স্যুইচ করুন — ${amount}`,
    updatePaymentMethod: 'পেমেন্ট পদ্ধতি আপডেট করুন',
    cancelSubscription: 'সাবস্ক্রিপশন বাতিল করুন',
    subscribeWithAmount: (amount) => `সাবস্ক্রাইব — ${amount}`,
    paymentHistory: 'পেমেন্ট ইতিহাস',
    invoiceDate: 'তারিখ',
    invoiceAmount: 'পরিমাণ',
    invoiceStatus: 'স্থিতি',
    invoiceColumn: 'ইনভয়েস',
    invoiceDownload: 'ডাউনলোড',
    invoicePending: 'মুলতুবি',
    invoicePaid: 'পরিশোধিত',
    noInvoices: 'এখনও কোনো Razorpay ইনভয়েস উপলব্ধ নেই।',
    backToPricing: 'মূল্যে ফিরে যান',
    errorRazorpayNotLoaded: 'Razorpay চেকআউট এখনও লোড হয়নি। পেজ রিফ্রেশ করে আবার চেষ্টা করুন।',
    errorCheckoutMissingId: 'চেকআউট প্রতিক্রিয়ায় subscription_id বা key_id অনুপস্থিত।',
    errorLoadShops: 'দোকান লোড করতে অক্ষম।',
    errorLoadEntitlement: 'সাবস্ক্রিপশন স্থিতি লোড করতে অক্ষম।',
    errorStartCheckout: 'চেকআউট শুরু করতে অক্ষম।',
    errorSwitchPlan: 'প্ল্যান পরিবর্তন করতে অক্ষম।',
    errorPaymentMethod: 'পেমেন্ট পদ্ধতি আপডেট করতে অক্ষম।',
    errorCancel: 'সাবস্ক্রিপশন বাতিল করতে অক্ষম।',
  },
  contact: {
    heading: 'সহায়তা যোগাযোগ',
    lead: 'সাবস্ক্রিপশন, ইনভয়েস, অ্যাকাউন্ট, রিফান্ড বা অ্যাপ সহায়তার জন্য, ইমেলে Samaan-Bol টিমের সাথে যোগাযোগ করুন।',
    emailHeading: 'ইমেল',
    developerHeading: 'ডেভেলপার যোগাযোগ',
    responseHeading: 'প্রতিক্রিয়ার সময়',
    responseBody: 'আমরা ২টি কার্যদিবসের মধ্যে প্রতিক্রিয়া জানানোর লক্ষ্য রাখি। রিফান্ড ও বিলিং অনুরোধের যাচাইয়ের জন্য Razorpay পেমেন্ট শনাক্তকারী প্রয়োজন হতে পারে।',
    businessHeading: 'ব্যবসায়িক ঠিকানা',
    businessBody: 'Samaan-Bol, ভারত। Razorpay/GST ইনভয়েস সম্মতির জন্য নিশ্চিত হলে নিবন্ধিত ব্যবসায়িক ঠিকানা ও GSTIN এখানে দেখানো হবে।',
  },
};

const ta: SubscriptionStrings = {
  brand: { tagline: 'இந்திய சில்லறை வணிகத்தின் இதயத்திற்காக கட்டப்பட்ட, குரல்-முதல் AI சரக்கு மேலாண்மை.' },
  nav: { features: 'அம்சங்கள்', ai: 'AI நுண்ணறிவு', pricing: 'விலை', account: 'கணக்கு', download: 'ஆப்பை பதிவிறக்கவும்' },
  footer: {
    product: 'தயாரிப்பு',
    company: 'நிறுவனம்',
    support: 'ஆதரவு',
    features: 'அம்சங்கள்',
    ai: 'AI நுண்ணறிவு',
    pricing: 'விலை',
    about: 'எங்களைப் பற்றி',
    blog: 'வலைப்பதிவு',
    careers: 'வேலைவாய்ப்புகள்',
    contact: 'தொடர்பு',
    account: 'கணக்கு',
    refund: 'பணத்திரும்பும் கொள்கை',
    privacy: 'தனியுரிமைக் கொள்கை',
    terms: 'சேவை விதிமுறைகள்',
    copyright: '© Samaan-Bol. இந்திய சில்லறை வணிகத்திற்கான குரல்-முதல் சரக்கு.',
  },
  plans: { monthlyLabel: 'மாதாந்திர', annualLabel: 'வருடாந்திர', monthlyDescription: 'பிரீமியம் — மாதாந்திர', annualDescription: 'பிரீமியம் — வருடாந்திர' },
  pricing: {
    heroTitle: 'பிரீமியம் ₹499/மாதம் அல்லது ₹3,999/ஆண்டு',
    heroLead:
      'பாதுகாப்பான Razorpay UPI ஆட்டோபேக்கு வலையில் சந்தாதாரராகவும். அப்ளிக்கேஷனுக்கு வெளியே பில்லிங்கை நிர்வகிக்கும் iOS பயனர்களுக்காக கட்டப்பட்டது, மற்றும் ஒரே இடத்தில் இன்வாய்ஸ், ரத்து செய்தல் மற்றும் கணக்கு கட்டுப்பாட்டை விரும்பும் ஒவ்வொரு கடை உரிமையாளருக்கும் பயனுள்ளது.',
    ctaSubscribe: 'சந்தா — உள்நுழைய',
    ctaOpenInApp: 'ஆப்பில் திற',
    planSelectorLabel: 'திட்ட தேர்வாளர்',
    billingIntervalLabel: 'பில்லிங் இடைவெளி',
    selectedPlan: 'தேர்ந்தெடுக்கப்பட்ட திட்டம்',
    annualSavings: 'சுமார் 33% சேமிக்கவும். உண்மையான விலை சுமார் ₹333/மாதம்.',
    monthlyFlexible: 'நெகிழ்வான மாதாந்திர பில்லிங். அடுத்த பில்லிங் சுழற்சிக்கு முன் ரத்து செய்யவும்.',
    subscribeWithAmount: (amount) => `சந்தா — ${amount}`,
    refundWindow: 'முதல் கட்டணத்தில் இருந்து 7-நாள் பணத்திரும்பும் காலம்',
    razorpaySecure: 'Razorpay மூலம் பாதுகாப்பான கட்டணம்',
    gstInvoice: 'Razorpay மூலம் GST இன்வாய்ஸ் ஆதரவு',
    comparisonHeading: 'உங்கள் கடைக்கு பொருந்தும் சரக்கு அமைப்பை தேர்வு செய்யுங்கள்',
    freeHeading: 'இலவசம்',
    premiumHeading: 'பிரீமியம்',
    freeFeatures: ['அடிப்படை தயாரிப்பு மேலாண்மை', 'ஒரு கடை', 'கைமுறை ஸ்டாக் உள்ளீடு', 'பார்கோடு ஸ்கேன்', 'அணி அழைப்புகள்', 'அத்தியாவசிய தணிக்கை தடம்'],
    premiumFeatures: [
      'இந்தி, ஆங்கிலம் மற்றும் பிராந்திய இந்திய மொழிகளில் குரல் AI',
      'AI ஸ்டாக் கணிப்புகள் மற்றும் காலாவதி எச்சரிக்கைகள்',
      'மேம்பட்ட பகுப்பாய்வு மற்றும் முழு சரக்கு வரலாறு',
      'வளரும் சில்லறை விற்பனையாளர்களுக்கான பல்-கடை ஆதரவு',
      'ஸ்டாக் முடிவதற்கு முன் AI வாங்கல்-பட்டியல் பரிந்துரைகள்',
      'தணிக்கை தடங்களுடன் அணி ஒத்துழைப்பு',
    ],
    secureBillingHeading: 'இந்திய கடைகளுக்கான பாதுகாப்பான பில்லிங்',
    trustStrip: ['Razorpay ஹோஸ்ட் செக்அவுட்', 'UPI ஆட்டோபே ஆதரவு', 'எப்போது வேண்டுமானாலும் ரத்து செய்', '7-நாள் பணத்திரும்பும் காலம்'],
    faqHeading: 'சந்தா வாங்குவதற்கு முன் கேள்விகள்',
    faq: [
      { q: 'UPI ஆட்டோபே என்றால் என்ன?', a: 'UPI ஆட்டோபே ஒரு முறை மீண்டும் நிகழும் ஆணையை அனுமதிக்க உங்களை அனுமதிக்கிறது, பின்னர் Razorpay RBI விதிகளின் கீழ் தானாகவே எதிர்கால சந்தா கட்டணங்களை சேகரிக்கிறது.' },
      { q: 'நான் எப்போது வேண்டுமானாலும் ரத்து செய்யலாமா?', a: 'ஆம். ரத்து செய்தல் எதிர்கால புதுப்பித்தல்களை நிறுத்துகிறது. பிரீமியம் அணுகல் செலுத்திய காலத்தின் இறுதி வரை தொடரும்.' },
      { q: 'எனக்கு GST இன்வாய்ஸ் கிடைக்குமா?', a: 'சந்தாவிற்கு பில்லிங் தகவல் கிடைக்கும் போது Razorpay மூலம் இன்வாய்ஸ்கள் வழங்கப்படுகின்றன.' },
      { q: 'என் கட்டணத் தகவல் பாதுகாப்பானதா?', a: 'Razorpay முக்கியமான கட்டண விவரங்களை கையாளுகிறது. Samaan-Bol அணுகலை நிர்வகிக்கத் தேவையான கட்டண மற்றும் சந்தா மெட்டாடேட்டாவை மட்டுமே பெறுகிறது.' },
    ],
  },
  account: {
    loadingSignIn: 'உள்நுழைவு நிலை ஏற்றப்படுகிறது...',
    loadingAccount: 'கணக்கு ஏற்றப்படுகிறது...',
    signedOutHeading: 'உங்கள் சந்தாவை நிர்வகிக்க உள்நுழைய',
    signedOutLead: 'Samaan-Bol ஆப்பில் நீங்கள் பயன்படுத்தும் அதே Clerk கணக்கு மின்னஞ்சலைப் பயன்படுத்தவும். iOS பயனர்கள் இங்கு வலையில் சந்தா மற்றும் பில்லிங்கை நிர்வகிக்கின்றனர்.',
    heading: 'கணக்கு',
    leadWithEmail: (email) => `${email}-க்கான கடை சந்தாக்கள், Razorpay செக்அவுட், இன்வாய்ஸ், ரத்துகள் மற்றும் கணக்கு அணுகலை நிர்வகிக்கவும்.`,
    accountFallback: 'உங்கள் Samaan-Bol கணக்கு',
    linkedShops: 'இணைக்கப்பட்ட கடைகள்',
    loadingShops: 'கடைகள் ஏற்றப்படுகின்றன...',
    noShops: 'சந்தா API எந்த கடையையும் திருப்பவில்லை.',
    shopRoleFallback: 'கடை அணுகல்',
    statusLoading: 'ஏற்றப்படுகிறது',
    statusActive: (interval) => `பிரீமியம் — ${interval}`,
    statusTrialEnds: (date) => `சோதனை — ${date}-இல் முடியும்`,
    statusPastDue: 'கட்டணம் தோல்வி',
    statusCanceled: 'ரத்து செய்யப்பட்டது',
    statusLegacyFree: 'பாரம்பரிய இலவசம்',
    statusNone: 'செயலில் சந்தா இல்லை',
    dateUnavailable: 'கிடைக்கவில்லை',
    selectShop: 'ஒரு கடையை தேர்வுசெய்க',
    renewsOn: (date) => `${date}-இல் புதுப்பிப்பு அல்லது மாற்றம்`,
    chooseIntervalPrompt: 'ஒரு பில்லிங் இடைவெளியை தேர்ந்தெடுத்து இந்த கடைக்கான Razorpay செக்அவுட்டைத் தொடங்கவும்.',
    currentPlan: (label) => `உங்கள் தற்போதைய திட்டம் ${label}. திட்டங்களை மாற்றுவதற்கு அல்லது கட்டண முறையை புதுப்பிக்க Razorpay-இல் ஒரு புதிய UPI ஆட்டோபே ஆணையை அங்கீகரிக்க வேண்டும்.`,
    switchToAnnual: (amount) => `வருடாந்திரத்திற்கு மாற்று — ${amount}`,
    switchToMonthly: (amount) => `மாதாந்திரத்திற்கு மாற்று — ${amount}`,
    updatePaymentMethod: 'கட்டண முறையை புதுப்பிக்கவும்',
    cancelSubscription: 'சந்தாவை ரத்து செய்',
    subscribeWithAmount: (amount) => `சந்தா — ${amount}`,
    paymentHistory: 'கட்டண வரலாறு',
    invoiceDate: 'தேதி',
    invoiceAmount: 'தொகை',
    invoiceStatus: 'நிலை',
    invoiceColumn: 'இன்வாய்ஸ்',
    invoiceDownload: 'பதிவிறக்கவும்',
    invoicePending: 'நிலுவையில்',
    invoicePaid: 'செலுத்தப்பட்டது',
    noInvoices: 'இன்னும் எந்த Razorpay இன்வாய்ஸும் கிடைக்கவில்லை.',
    backToPricing: 'விலையக்கு திரும்பு',
    errorRazorpayNotLoaded: 'Razorpay செக்அவுட் இன்னும் ஏற்றப்படவில்லை. பக்கத்தை ரீஃப்ரெஷ் செய்து மீண்டும் முயற்சிக்கவும்.',
    errorCheckoutMissingId: 'செக்அவுட் பதிலில் subscription_id அல்லது key_id இல்லை.',
    errorLoadShops: 'கடைகளை ஏற்ற முடியவில்லை.',
    errorLoadEntitlement: 'சந்தா நிலையை ஏற்ற முடியவில்லை.',
    errorStartCheckout: 'செக்அவுட்டைத் தொடங்க முடியவில்லை.',
    errorSwitchPlan: 'திட்டத்தை மாற்ற முடியவில்லை.',
    errorPaymentMethod: 'கட்டண முறையை புதுப்பிக்க முடியவில்லை.',
    errorCancel: 'சந்தாவை ரத்து செய்ய முடியவில்லை.',
  },
  contact: {
    heading: 'ஆதரவைத் தொடர்புகொள்ளவும்',
    lead: 'சந்தா, இன்வாய்ஸ், கணக்கு, பணத்திரும்பல் அல்லது ஆப் ஆதரவுக்கு, மின்னஞ்சல் மூலம் Samaan-Bol குழுவைத் தொடர்புகொள்ளவும்.',
    emailHeading: 'மின்னஞ்சல்',
    developerHeading: 'டெவலப்பர் தொடர்பு',
    responseHeading: 'பதில் நேரம்',
    responseBody: '2 வேலை நாட்களுக்குள் பதிலளிக்க முயற்சிக்கிறோம். பணத்திரும்பல் மற்றும் பில்லிங் கோரிக்கைகளுக்கு சரிபார்ப்பிற்காக Razorpay கட்டண அடையாளங்காட்டிகள் தேவைப்படலாம்.',
    businessHeading: 'வணிக முகவரி',
    businessBody: 'Samaan-Bol, இந்தியா. Razorpay/GST இன்வாய்ஸ் இணக்கத்திற்கு உறுதிப்படுத்தப்பட்ட பிறகு பதிவு செய்யப்பட்ட வணிக முகவரி மற்றும் GSTIN இங்கு காட்டப்படும்.',
  },
};

const te: SubscriptionStrings = {
  brand: { tagline: 'భారతీయ రిటైల్ హృదయం కోసం నిర్మించబడిన, వాయిస్-ఫస్ట్ AI ఇన్వెంటరీ నిర్వహణ.' },
  nav: { features: 'ఫీచర్లు', ai: 'AI ఇంటెలిజెన్స్', pricing: 'ధర', account: 'ఖాతా', download: 'యాప్ డౌన్‌లోడ్ చేయండి' },
  footer: {
    product: 'ఉత్పత్తి',
    company: 'కంపెనీ',
    support: 'మద్దతు',
    features: 'ఫీచర్లు',
    ai: 'AI ఇంటెలిజెన్స్',
    pricing: 'ధర',
    about: 'మా గురించి',
    blog: 'బ్లాగ్',
    careers: 'కెరీర్లు',
    contact: 'సంప్రదించండి',
    account: 'ఖాతా',
    refund: 'రీఫండ్ విధానం',
    privacy: 'గోప్యతా విధానం',
    terms: 'సేవా నిబంధనలు',
    copyright: '© Samaan-Bol. భారతీయ రిటైల్ కోసం వాయిస్-ఫస్ట్ ఇన్వెంటరీ.',
  },
  plans: { monthlyLabel: 'నెలవారీ', annualLabel: 'వార్షిక', monthlyDescription: 'ప్రీమియం — నెలవారీ', annualDescription: 'ప్రీమియం — వార్షిక' },
  pricing: {
    heroTitle: 'ప్రీమియం ₹499/నెల లేదా ₹3,999/సంవత్సరం',
    heroLead:
      'సురక్షితమైన Razorpay UPI ఆటోపే కోసం వెబ్‌లో సబ్‌స్క్రైబ్ చేయండి. యాప్ వెలుపల బిల్లింగ్‌ను నిర్వహించే iOS వినియోగదారుల కోసం నిర్మించబడింది, మరియు ఒకే చోట ఇన్వాయిస్‌లు, రద్దు చేయడం మరియు ఖాతా నియంత్రణ కోరుకునే ప్రతి దుకాణదారునికి ఉపయోగకరమైనది.',
    ctaSubscribe: 'సబ్‌స్క్రైబ్ — సైన్ ఇన్',
    ctaOpenInApp: 'యాప్‌లో తెరవండి',
    planSelectorLabel: 'ప్లాన్ ఎంపికదారు',
    billingIntervalLabel: 'బిల్లింగ్ విరామం',
    selectedPlan: 'ఎంచుకున్న ప్లాన్',
    annualSavings: 'సుమారు 33% ఆదా చేయండి. ప్రభావవంతమైన ధర నెలకు సుమారు ₹333.',
    monthlyFlexible: 'సౌకర్యవంతమైన నెలవారీ బిల్లింగ్. తదుపరి బిల్లింగ్ చక్రానికి ముందు రద్దు చేయండి.',
    subscribeWithAmount: (amount) => `సబ్‌స్క్రైబ్ — ${amount}`,
    refundWindow: 'మొదటి ఛార్జ్ నుండి 7-రోజుల రీఫండ్ విండో',
    razorpaySecure: 'Razorpay ద్వారా సురక్షితమైన చెల్లింపులు',
    gstInvoice: 'Razorpay ద్వారా GST ఇన్వాయిస్ మద్దతు',
    comparisonHeading: 'మీ దుకాణానికి సరిపోయే ఇన్వెంటరీ సిస్టమ్‌ను ఎంచుకోండి',
    freeHeading: 'ఉచితం',
    premiumHeading: 'ప్రీమియం',
    freeFeatures: ['ప్రాథమిక ఉత్పత్తి నిర్వహణ', 'ఒక దుకాణం', 'మాన్యువల్ స్టాక్ ఎంట్రీ', 'బార్‌కోడ్ స్కాన్', 'జట్టు ఆహ్వానాలు', 'అవసరమైన ఆడిట్ ట్రయిల్'],
    premiumFeatures: [
      'హిందీ, ఆంగ్లం మరియు ప్రాంతీయ భారతీయ భాషలలో వాయిస్ AI',
      'AI స్టాక్ అంచనాలు మరియు గడువు హెచ్చరికలు',
      'అధునాతన విశ్లేషణ మరియు పూర్తి ఇన్వెంటరీ చరిత్ర',
      'పెరుగుతున్న రిటైలర్ల కోసం బహుళ-దుకాణ మద్దతు',
      'స్టాక్ అయిపోయే ముందు AI కొనుగోలు-జాబితా సూచనలు',
      'ఆడిట్ ట్రయిల్‌తో జట్టు సహకారం',
    ],
    secureBillingHeading: 'భారతీయ దుకాణాల కోసం సురక్షితమైన బిల్లింగ్',
    trustStrip: ['Razorpay హోస్ట్ చేసిన చెక్‌అవుట్', 'UPI ఆటోపే మద్దతు', 'ఎప్పుడైనా రద్దు చేయండి', '7-రోజుల రీఫండ్ విండో'],
    faqHeading: 'సబ్‌స్క్రైబ్ చేయడానికి ముందు ప్రశ్నలు',
    faq: [
      { q: 'UPI ఆటోపే అంటే ఏమిటి?', a: 'UPI ఆటోపే మీరు ఒకసారి పునరావృత మాండేట్‌ను ఆమోదించడానికి అనుమతిస్తుంది, తరువాత Razorpay RBI నియమాల కింద భవిష్యత్ సబ్‌స్క్రిప్షన్ చెల్లింపులను ఆటోమేటిక్‌గా సేకరిస్తుంది.' },
      { q: 'నేను ఎప్పుడైనా రద్దు చేయగలనా?', a: 'అవును. రద్దు చేయడం భవిష్యత్ పునరుద్ధరణలను ఆపుతుంది. చెల్లించిన కాలం ముగిసే వరకు ప్రీమియం యాక్సెస్ కొనసాగుతుంది.' },
      { q: 'నాకు GST ఇన్వాయిస్ లభిస్తుందా?', a: 'సబ్‌స్క్రిప్షన్ కోసం బిల్లింగ్ సమాచారం అందుబాటులో ఉన్నప్పుడు Razorpay ద్వారా ఇన్వాయిస్‌లు జారీ చేయబడతాయి.' },
      { q: 'నా చెల్లింపు సమాచారం సురక్షితంగా ఉందా?', a: 'Razorpay సున్నితమైన చెల్లింపు వివరాలను నిర్వహిస్తుంది. యాక్సెస్‌ను నిర్వహించడానికి అవసరమైన చెల్లింపు మరియు సబ్‌స్క్రిప్షన్ మెటాడేటాను మాత్రమే Samaan-Bol అందుకుంటుంది.' },
    ],
  },
  account: {
    loadingSignIn: 'సైన్-ఇన్ స్థితి లోడ్ అవుతోంది...',
    loadingAccount: 'ఖాతా లోడ్ అవుతోంది...',
    signedOutHeading: 'మీ సబ్‌స్క్రిప్షన్‌ను నిర్వహించడానికి సైన్ ఇన్ చేయండి',
    signedOutLead: 'Samaan-Bol యాప్‌లో మీరు ఉపయోగించే అదే Clerk ఖాతా ఇమెయిల్‌ను ఉపయోగించండి. iOS వినియోగదారులు ఇక్కడ వెబ్‌లో సబ్‌స్క్రైబ్ చేస్తారు మరియు బిల్లింగ్‌ను నిర్వహిస్తారు.',
    heading: 'ఖాతా',
    leadWithEmail: (email) => `${email} కోసం దుకాణ సబ్‌స్క్రిప్షన్‌లు, Razorpay చెక్‌అవుట్, ఇన్వాయిస్‌లు, రద్దులు మరియు ఖాతా యాక్సెస్‌ను నిర్వహించండి.`,
    accountFallback: 'మీ Samaan-Bol ఖాతా',
    linkedShops: 'లింక్ చేయబడిన దుకాణాలు',
    loadingShops: 'దుకాణాలు లోడ్ అవుతున్నాయి...',
    noShops: 'సబ్‌స్క్రిప్షన్ API ఏ దుకాణాన్ని తిరిగి ఇవ్వలేదు.',
    shopRoleFallback: 'దుకాణ యాక్సెస్',
    statusLoading: 'లోడ్ అవుతోంది',
    statusActive: (interval) => `ప్రీమియం — ${interval}`,
    statusTrialEnds: (date) => `ట్రయల్ — ${date}-న ముగుస్తుంది`,
    statusPastDue: 'చెల్లింపు విఫలమైంది',
    statusCanceled: 'రద్దు చేయబడింది',
    statusLegacyFree: 'లెగసీ ఉచితం',
    statusNone: 'క్రియాశీల సబ్‌స్క్రిప్షన్ లేదు',
    dateUnavailable: 'అందుబాటులో లేదు',
    selectShop: 'ఒక దుకాణాన్ని ఎంచుకోండి',
    renewsOn: (date) => `${date}-న పునరుద్ధరణ లేదా మార్పులు`,
    chooseIntervalPrompt: 'ఒక బిల్లింగ్ విరామాన్ని ఎంచుకుని, ఈ దుకాణం కోసం Razorpay చెక్‌అవుట్‌ను ప్రారంభించండి.',
    currentPlan: (label) => `మీ ప్రస్తుత ప్లాన్ ${label}. ప్లాన్‌లను మార్చడానికి లేదా చెల్లింపు పద్ధతిని నవీకరించడానికి Razorpay-లో కొత్త UPI ఆటోపే మాండేట్‌ను అధికారం ఇవ్వాలి.`,
    switchToAnnual: (amount) => `వార్షికానికి మారండి — ${amount}`,
    switchToMonthly: (amount) => `నెలవారీకి మారండి — ${amount}`,
    updatePaymentMethod: 'చెల్లింపు పద్ధతిని నవీకరించండి',
    cancelSubscription: 'సబ్‌స్క్రిప్షన్‌ను రద్దు చేయండి',
    subscribeWithAmount: (amount) => `సబ్‌స్క్రైబ్ — ${amount}`,
    paymentHistory: 'చెల్లింపు చరిత్ర',
    invoiceDate: 'తేదీ',
    invoiceAmount: 'మొత్తం',
    invoiceStatus: 'స్థితి',
    invoiceColumn: 'ఇన్వాయిస్',
    invoiceDownload: 'డౌన్‌లోడ్',
    invoicePending: 'పెండింగ్',
    invoicePaid: 'చెల్లించబడింది',
    noInvoices: 'ఇంకా ఏ Razorpay ఇన్వాయిస్‌లు అందుబాటులో లేవు.',
    backToPricing: 'ధరకు తిరిగి',
    errorRazorpayNotLoaded: 'Razorpay చెక్‌అవుట్ ఇంకా లోడ్ కాలేదు. పేజీని రిఫ్రెష్ చేసి మళ్లీ ప్రయత్నించండి.',
    errorCheckoutMissingId: 'చెక్‌అవుట్ ప్రతిస్పందనలో subscription_id లేదా key_id లేదు.',
    errorLoadShops: 'దుకాణాలను లోడ్ చేయలేకపోయింది.',
    errorLoadEntitlement: 'సబ్‌స్క్రిప్షన్ స్థితిని లోడ్ చేయలేకపోయింది.',
    errorStartCheckout: 'చెక్‌అవుట్‌ను ప్రారంభించలేకపోయింది.',
    errorSwitchPlan: 'ప్లాన్‌ను మార్చలేకపోయింది.',
    errorPaymentMethod: 'చెల్లింపు పద్ధతిని నవీకరించలేకపోయింది.',
    errorCancel: 'సబ్‌స్క్రిప్షన్‌ను రద్దు చేయలేకపోయింది.',
  },
  contact: {
    heading: 'మద్దతును సంప్రదించండి',
    lead: 'సబ్‌స్క్రిప్షన్, ఇన్వాయిస్, ఖాతా, రీఫండ్ లేదా యాప్ మద్దతు కోసం, ఇమెయిల్ ద్వారా Samaan-Bol బృందాన్ని సంప్రదించండి.',
    emailHeading: 'ఇమెయిల్',
    developerHeading: 'డెవలపర్ సంప్రదింపు',
    responseHeading: 'ప్రతిస్పందన సమయం',
    responseBody: 'మేము 2 వ్యాపార రోజులలో ప్రతిస్పందించడానికి లక్ష్యంగా పెట్టుకుంటాము. రీఫండ్ మరియు బిల్లింగ్ అభ్యర్థనలకు ధృవీకరణ కోసం Razorpay చెల్లింపు గుర్తింపులు అవసరం కావచ్చు.',
    businessHeading: 'వ్యాపార చిరునామా',
    businessBody: 'Samaan-Bol, భారతదేశం. Razorpay/GST ఇన్వాయిస్ సమ్మతి కోసం నిర్ధారించబడిన తర్వాత నమోదిత వ్యాపార చిరునామా మరియు GSTIN ఇక్కడ చూపబడతాయి.',
  },
};

const mr: SubscriptionStrings = {
  brand: { tagline: 'भारतीय किरकोळ व्यवसायाच्या हृदयासाठी तयार केलेले, व्हॉइस-फर्स्ट AI इन्व्हेंटरी व्यवस्थापन.' },
  nav: { features: 'वैशिष्ट्ये', ai: 'AI इंटेलिजन्स', pricing: 'किंमत', account: 'खाते', download: 'अ‍ॅप डाउनलोड करा' },
  footer: {
    product: 'उत्पादन',
    company: 'कंपनी',
    support: 'सहाय्य',
    features: 'वैशिष्ट्ये',
    ai: 'AI इंटेलिजन्स',
    pricing: 'किंमत',
    about: 'आमच्याबद्दल',
    blog: 'ब्लॉग',
    careers: 'करिअर',
    contact: 'संपर्क',
    account: 'खाते',
    refund: 'परतावा धोरण',
    privacy: 'गोपनीयता धोरण',
    terms: 'सेवा अटी',
    copyright: '© Samaan-Bol. भारतीय किरकोळ व्यवसायासाठी व्हॉइस-फर्स्ट इन्व्हेंटरी.',
  },
  plans: { monthlyLabel: 'मासिक', annualLabel: 'वार्षिक', monthlyDescription: 'प्रीमियम — मासिक', annualDescription: 'प्रीमियम — वार्षिक' },
  pricing: {
    heroTitle: 'प्रीमियम ₹499/महिना किंवा ₹3,999/वर्ष',
    heroLead:
      'सुरक्षित Razorpay UPI ऑटोपे साठी वेबवर सदस्यता घ्या. अ‍ॅपच्या बाहेर बिलिंग व्यवस्थापित करणाऱ्या iOS वापरकर्त्यांसाठी तयार केलेले, आणि एकाच ठिकाणी इनव्हॉइस, रद्द करणे आणि खाते नियंत्रण हवे असलेल्या प्रत्येक दुकानदारासाठी उपयुक्त.',
    ctaSubscribe: 'सदस्यता — साइन इन',
    ctaOpenInApp: 'अ‍ॅपमध्ये उघडा',
    planSelectorLabel: 'योजना निवडक',
    billingIntervalLabel: 'बिलिंग कालावधी',
    selectedPlan: 'निवडलेली योजना',
    annualSavings: 'सुमारे 33% बचत करा. प्रभावी किंमत सुमारे ₹333/महिना.',
    monthlyFlexible: 'लवचिक मासिक बिलिंग. पुढील बिलिंग चक्राच्या आधी रद्द करा.',
    subscribeWithAmount: (amount) => `सदस्यता — ${amount}`,
    refundWindow: 'पहिल्या शुल्कापासून 7-दिवसांची परतावा विंडो',
    razorpaySecure: 'Razorpay द्वारे सुरक्षित पेमेंट',
    gstInvoice: 'Razorpay द्वारे GST इनव्हॉइस सहाय्य',
    comparisonHeading: 'तुमच्या दुकानाला साजेशी इन्व्हेंटरी सिस्टम निवडा',
    freeHeading: 'विनामूल्य',
    premiumHeading: 'प्रीमियम',
    freeFeatures: ['मूलभूत उत्पादन व्यवस्थापन', 'एक दुकान', 'मॅन्युअल स्टॉक एंट्री', 'बारकोड स्कॅन', 'टीम आमंत्रणे', 'आवश्यक ऑडिट ट्रेल'],
    premiumFeatures: [
      'हिंदी, इंग्रजी आणि प्रादेशिक भारतीय भाषांमध्ये व्हॉइस AI',
      'AI स्टॉक भविष्यवाणी आणि कालबाह्यता सूचना',
      'प्रगत विश्लेषण आणि संपूर्ण इन्व्हेंटरी इतिहास',
      'वाढत्या किरकोळ विक्रेत्यांसाठी मल्टी-शॉप सपोर्ट',
      'स्टॉक संपण्याआधी AI खरेदी-यादी सूचना',
      'ऑडिट ट्रेलसह टीम सहयोग',
    ],
    secureBillingHeading: 'भारतीय दुकानांसाठी सुरक्षित बिलिंग',
    trustStrip: ['Razorpay होस्ट केलेले चेकआउट', 'UPI ऑटोपे समर्थित', 'कधीही रद्द करा', '7-दिवसांची परतावा विंडो'],
    faqHeading: 'सदस्यता घेण्याआधी प्रश्न',
    faq: [
      { q: 'UPI ऑटोपे म्हणजे काय?', a: 'UPI ऑटोपे तुम्हाला एकदा आवर्ती मॅन्डेट मंजूर करण्याची परवानगी देते, नंतर Razorpay RBI नियमांनुसार भविष्यातील सदस्यता पेमेंट स्वयंचलितपणे संकलित करते.' },
      { q: 'मी कधीही रद्द करू शकतो का?', a: 'होय. रद्द करणे भविष्यातील नूतनीकरण थांबवते. प्रीमियम प्रवेश सशुल्क कालावधीच्या शेवटपर्यंत सुरू राहतो.' },
      { q: 'मला GST इनव्हॉइस मिळेल का?', a: 'सदस्यतेसाठी बिलिंग माहिती उपलब्ध असताना Razorpay द्वारे इनव्हॉइस जारी केले जातात.' },
      { q: 'माझी पेमेंट माहिती सुरक्षित आहे का?', a: 'Razorpay संवेदनशील पेमेंट तपशील हाताळते. Samaan-Bol फक्त प्रवेश व्यवस्थापित करण्यासाठी आवश्यक पेमेंट आणि सदस्यता मेटाडेटा प्राप्त करते.' },
    ],
  },
  account: {
    loadingSignIn: 'साइन-इन स्थिती लोड होत आहे...',
    loadingAccount: 'खाते लोड होत आहे...',
    signedOutHeading: 'तुमची सदस्यता व्यवस्थापित करण्यासाठी साइन इन करा',
    signedOutLead: 'Samaan-Bol अ‍ॅपमध्ये तुम्ही वापरता तोच Clerk खाते ईमेल वापरा. iOS वापरकर्ते येथे वेबवर सदस्यता घेतात आणि बिलिंग व्यवस्थापित करतात.',
    heading: 'खाते',
    leadWithEmail: (email) => `${email} साठी दुकान सदस्यता, Razorpay चेकआउट, इनव्हॉइस, रद्द करणे आणि खाते प्रवेश व्यवस्थापित करा.`,
    accountFallback: 'तुमचे Samaan-Bol खाते',
    linkedShops: 'जोडलेली दुकाने',
    loadingShops: 'दुकाने लोड होत आहेत...',
    noShops: 'सदस्यता API ने कोणतेही दुकान परत केले नाही.',
    shopRoleFallback: 'दुकान प्रवेश',
    statusLoading: 'लोड होत आहे',
    statusActive: (interval) => `प्रीमियम — ${interval}`,
    statusTrialEnds: (date) => `ट्रायल — ${date} रोजी संपेल`,
    statusPastDue: 'पेमेंट अयशस्वी',
    statusCanceled: 'रद्द',
    statusLegacyFree: 'लीगसी विनामूल्य',
    statusNone: 'सक्रिय सदस्यता नाही',
    dateUnavailable: 'उपलब्ध नाही',
    selectShop: 'एक दुकान निवडा',
    renewsOn: (date) => `${date} रोजी नूतनीकरण किंवा बदल`,
    chooseIntervalPrompt: 'एक बिलिंग कालावधी निवडा आणि या दुकानासाठी Razorpay चेकआउट सुरू करा.',
    currentPlan: (label) => `तुमची सध्याची योजना ${label} आहे. योजना बदलण्यासाठी किंवा पेमेंट पद्धत अद्यतनित करण्यासाठी Razorpay वर नवीन UPI ऑटोपे मॅन्डेट अधिकृत करणे आवश्यक आहे.`,
    switchToAnnual: (amount) => `वार्षिकवर स्विच करा — ${amount}`,
    switchToMonthly: (amount) => `मासिकवर स्विच करा — ${amount}`,
    updatePaymentMethod: 'पेमेंट पद्धत अद्यतनित करा',
    cancelSubscription: 'सदस्यता रद्द करा',
    subscribeWithAmount: (amount) => `सदस्यता — ${amount}`,
    paymentHistory: 'पेमेंट इतिहास',
    invoiceDate: 'तारीख',
    invoiceAmount: 'रक्कम',
    invoiceStatus: 'स्थिती',
    invoiceColumn: 'इनव्हॉइस',
    invoiceDownload: 'डाउनलोड',
    invoicePending: 'प्रलंबित',
    invoicePaid: 'भरलेले',
    noInvoices: 'अद्याप कोणतेही Razorpay इनव्हॉइस उपलब्ध नाहीत.',
    backToPricing: 'किमतीकडे परत',
    errorRazorpayNotLoaded: 'Razorpay चेकआउट अद्याप लोड झालेले नाही. पेज रिफ्रेश करा आणि पुन्हा प्रयत्न करा.',
    errorCheckoutMissingId: 'चेकआउट प्रतिसादात subscription_id किंवा key_id गहाळ आहे.',
    errorLoadShops: 'दुकाने लोड करण्यात अक्षम.',
    errorLoadEntitlement: 'सदस्यता स्थिती लोड करण्यात अक्षम.',
    errorStartCheckout: 'चेकआउट सुरू करण्यात अक्षम.',
    errorSwitchPlan: 'योजना बदलण्यात अक्षम.',
    errorPaymentMethod: 'पेमेंट पद्धत अद्यतनित करण्यात अक्षम.',
    errorCancel: 'सदस्यता रद्द करण्यात अक्षम.',
  },
  contact: {
    heading: 'सहाय्य संपर्क',
    lead: 'सदस्यता, इनव्हॉइस, खाते, परतावा किंवा अ‍ॅप सहाय्यासाठी, ईमेलद्वारे Samaan-Bol टीमशी संपर्क साधा.',
    emailHeading: 'ईमेल',
    developerHeading: 'डेव्हलपर संपर्क',
    responseHeading: 'प्रतिसाद वेळ',
    responseBody: 'आम्ही 2 कामकाजाच्या दिवसांत प्रतिसाद देण्याचे लक्ष्य ठेवतो. परतावा आणि बिलिंग विनंत्यांसाठी पडताळणीसाठी Razorpay पेमेंट ओळखकर्ते आवश्यक असू शकतात.',
    businessHeading: 'व्यावसायिक पत्ता',
    businessBody: 'Samaan-Bol, भारत. Razorpay/GST इनव्हॉइस अनुपालनासाठी पुष्टी झाल्यावर नोंदणीकृत व्यावसायिक पत्ता आणि GSTIN येथे दर्शविला जाईल.',
  },
};

const kn: SubscriptionStrings = {
  brand: { tagline: 'ಭಾರತೀಯ ಚಿಲ್ಲರೆ ವ್ಯಾಪಾರದ ಹೃದಯಕ್ಕಾಗಿ ನಿರ್ಮಿಸಲಾದ, ಧ್ವನಿ-ಮೊದಲ AI ದಾಸ್ತಾನು ನಿರ್ವಹಣೆ.' },
  nav: { features: 'ವೈಶಿಷ್ಟ್ಯಗಳು', ai: 'AI ಬುದ್ಧಿಮತ್ತೆ', pricing: 'ಬೆಲೆ', account: 'ಖಾತೆ', download: 'ಆಪ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ' },
  footer: {
    product: 'ಉತ್ಪನ್ನ',
    company: 'ಕಂಪನಿ',
    support: 'ಬೆಂಬಲ',
    features: 'ವೈಶಿಷ್ಟ್ಯಗಳು',
    ai: 'AI ಬುದ್ಧಿಮತ್ತೆ',
    pricing: 'ಬೆಲೆ',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    blog: 'ಬ್ಲಾಗ್',
    careers: 'ಉದ್ಯೋಗಗಳು',
    contact: 'ಸಂಪರ್ಕಿಸಿ',
    account: 'ಖಾತೆ',
    refund: 'ಮರುಪಾವತಿ ನೀತಿ',
    privacy: 'ಗೌಪ್ಯತೆ ನೀತಿ',
    terms: 'ಸೇವಾ ನಿಯಮಗಳು',
    copyright: '© Samaan-Bol. ಭಾರತೀಯ ಚಿಲ್ಲರೆ ವ್ಯಾಪಾರಕ್ಕಾಗಿ ಧ್ವನಿ-ಮೊದಲ ದಾಸ್ತಾನು.',
  },
  plans: { monthlyLabel: 'ಮಾಸಿಕ', annualLabel: 'ವಾರ್ಷಿಕ', monthlyDescription: 'ಪ್ರೀಮಿಯಂ — ಮಾಸಿಕ', annualDescription: 'ಪ್ರೀಮಿಯಂ — ವಾರ್ಷಿಕ' },
  pricing: {
    heroTitle: 'ಪ್ರೀಮಿಯಂ ₹499/ತಿಂಗಳು ಅಥವಾ ₹3,999/ವರ್ಷ',
    heroLead:
      'ಸುರಕ್ಷಿತ Razorpay UPI ಆಟೋಪೇಗಾಗಿ ವೆಬ್‌ನಲ್ಲಿ ಚಂದಾದಾರರಾಗಿ. ಆಪ್‌ನ ಹೊರಗೆ ಬಿಲ್ಲಿಂಗ್ ನಿರ್ವಹಿಸುವ iOS ಬಳಕೆದಾರರಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ, ಮತ್ತು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ಇನ್‌ವಾಯ್ಸ್, ರದ್ದುಗೊಳಿಸುವಿಕೆ ಮತ್ತು ಖಾತೆ ನಿಯಂತ್ರಣವನ್ನು ಬಯಸುವ ಪ್ರತಿ ಅಂಗಡಿಯ ಮಾಲೀಕರಿಗೆ ಉಪಯುಕ್ತವಾಗಿದೆ.',
    ctaSubscribe: 'ಚಂದಾದಾರಿಕೆ — ಸೈನ್ ಇನ್',
    ctaOpenInApp: 'ಆಪ್‌ನಲ್ಲಿ ತೆರೆಯಿರಿ',
    planSelectorLabel: 'ಯೋಜನೆ ಆಯ್ಕೆಗಾರ',
    billingIntervalLabel: 'ಬಿಲ್ಲಿಂಗ್ ಮಧ್ಯಂತರ',
    selectedPlan: 'ಆಯ್ಕೆಮಾಡಿದ ಯೋಜನೆ',
    annualSavings: 'ಸುಮಾರು 33% ಉಳಿಸಿ. ಪರಿಣಾಮಕಾರಿ ಬೆಲೆ ತಿಂಗಳಿಗೆ ಸುಮಾರು ₹333.',
    monthlyFlexible: 'ಹೊಂದಿಕೊಳ್ಳುವ ಮಾಸಿಕ ಬಿಲ್ಲಿಂಗ್. ಮುಂದಿನ ಬಿಲ್ಲಿಂಗ್ ಚಕ್ರದ ಮೊದಲು ರದ್ದುಗೊಳಿಸಿ.',
    subscribeWithAmount: (amount) => `ಚಂದಾದಾರಿಕೆ — ${amount}`,
    refundWindow: 'ಮೊದಲ ಶುಲ್ಕದಿಂದ 7-ದಿನಗಳ ಮರುಪಾವತಿ ಅವಧಿ',
    razorpaySecure: 'Razorpay ಮೂಲಕ ಸುರಕ್ಷಿತ ಪಾವತಿಗಳು',
    gstInvoice: 'Razorpay ಮೂಲಕ GST ಇನ್‌ವಾಯ್ಸ್ ಬೆಂಬಲ',
    comparisonHeading: 'ನಿಮ್ಮ ಅಂಗಡಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ದಾಸ್ತಾನು ವ್ಯವಸ್ಥೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    freeHeading: 'ಉಚಿತ',
    premiumHeading: 'ಪ್ರೀಮಿಯಂ',
    freeFeatures: ['ಮೂಲ ಉತ್ಪನ್ನ ನಿರ್ವಹಣೆ', 'ಒಂದು ಅಂಗಡಿ', 'ಕೈಯಿಂದ ಸ್ಟಾಕ್ ನಮೂದು', 'ಬಾರ್‌ಕೋಡ್ ಸ್ಕ್ಯಾನ್', 'ತಂಡದ ಆಮಂತ್ರಣಗಳು', 'ಅಗತ್ಯ ಆಡಿಟ್ ಟ್ರಯಲ್'],
    premiumFeatures: [
      'ಹಿಂದಿ, ಇಂಗ್ಲಿಷ್ ಮತ್ತು ಪ್ರಾದೇಶಿಕ ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಧ್ವನಿ AI',
      'AI ಸ್ಟಾಕ್ ಮುನ್ಸೂಚನೆಗಳು ಮತ್ತು ಅವಧಿ ಮುಗಿಯುವ ಎಚ್ಚರಿಕೆಗಳು',
      'ಸುಧಾರಿತ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಪೂರ್ಣ ದಾಸ್ತಾನು ಇತಿಹಾಸ',
      'ಬೆಳೆಯುತ್ತಿರುವ ಚಿಲ್ಲರೆ ವ್ಯಾಪಾರಿಗಳಿಗೆ ಬಹು-ಅಂಗಡಿ ಬೆಂಬಲ',
      'ಸ್ಟಾಕ್ ಮುಗಿಯುವ ಮೊದಲು AI ಖರೀದಿ-ಪಟ್ಟಿ ಸಲಹೆಗಳು',
      'ಆಡಿಟ್ ಟ್ರಯಲ್‌ಗಳೊಂದಿಗೆ ತಂಡ ಸಹಯೋಗ',
    ],
    secureBillingHeading: 'ಭಾರತೀಯ ಅಂಗಡಿಗಳಿಗೆ ಸುರಕ್ಷಿತ ಬಿಲ್ಲಿಂಗ್',
    trustStrip: ['Razorpay ಹೋಸ್ಟ್ ಮಾಡಿದ ಚೆಕ್‌ಔಟ್', 'UPI ಆಟೋಪೇ ಬೆಂಬಲಿತ', 'ಯಾವಾಗ ಬೇಕಾದರೂ ರದ್ದುಗೊಳಿಸಿ', '7-ದಿನಗಳ ಮರುಪಾವತಿ ಅವಧಿ'],
    faqHeading: 'ಚಂದಾದಾರಿಕೆ ಮೊದಲು ಪ್ರಶ್ನೆಗಳು',
    faq: [
      { q: 'UPI ಆಟೋಪೇ ಎಂದರೇನು?', a: 'UPI ಆಟೋಪೇ ನೀವು ಒಮ್ಮೆ ಮರುಕಳಿಸುವ ಮ್ಯಾಂಡೇಟ್ ಅನ್ನು ಅನುಮೋದಿಸಲು ಅನುಮತಿಸುತ್ತದೆ, ನಂತರ Razorpay RBI ನಿಯಮಗಳ ಅಡಿಯಲ್ಲಿ ಭವಿಷ್ಯದ ಚಂದಾದಾರಿಕೆ ಪಾವತಿಗಳನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಂಗ್ರಹಿಸುತ್ತದೆ.' },
      { q: 'ನಾನು ಯಾವಾಗ ಬೇಕಾದರೂ ರದ್ದುಗೊಳಿಸಬಹುದೇ?', a: 'ಹೌದು. ರದ್ದುಗೊಳಿಸುವಿಕೆ ಭವಿಷ್ಯದ ನವೀಕರಣಗಳನ್ನು ನಿಲ್ಲಿಸುತ್ತದೆ. ಪಾವತಿಸಿದ ಅವಧಿಯ ಕೊನೆಯವರೆಗೆ ಪ್ರೀಮಿಯಂ ಪ್ರವೇಶ ಮುಂದುವರಿಯುತ್ತದೆ.' },
      { q: 'ನನಗೆ GST ಇನ್‌ವಾಯ್ಸ್ ಸಿಗುತ್ತದೆಯೇ?', a: 'ಚಂದಾದಾರಿಕೆಗೆ ಬಿಲ್ಲಿಂಗ್ ಮಾಹಿತಿ ಲಭ್ಯವಿರುವಾಗ Razorpay ಮೂಲಕ ಇನ್‌ವಾಯ್ಸ್‌ಗಳನ್ನು ನೀಡಲಾಗುತ್ತದೆ.' },
      { q: 'ನನ್ನ ಪಾವತಿ ಮಾಹಿತಿ ಸುರಕ್ಷಿತವಾಗಿದೆಯೇ?', a: 'Razorpay ಸೂಕ್ಷ್ಮ ಪಾವತಿ ವಿವರಗಳನ್ನು ನಿರ್ವಹಿಸುತ್ತದೆ. ಪ್ರವೇಶ ನಿರ್ವಹಣೆಗೆ ಅಗತ್ಯವಿರುವ ಪಾವತಿ ಮತ್ತು ಚಂದಾದಾರಿಕೆ ಮೆಟಾಡೇಟಾವನ್ನು ಮಾತ್ರ Samaan-Bol ಸ್ವೀಕರಿಸುತ್ತದೆ.' },
    ],
  },
  account: {
    loadingSignIn: 'ಸೈನ್-ಇನ್ ಸ್ಥಿತಿ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    loadingAccount: 'ಖಾತೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    signedOutHeading: 'ನಿಮ್ಮ ಚಂದಾದಾರಿಕೆಯನ್ನು ನಿರ್ವಹಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    signedOutLead: 'Samaan-Bol ಆಪ್‌ನಲ್ಲಿ ನೀವು ಬಳಸುವ ಅದೇ Clerk ಖಾತೆ ಇಮೇಲ್ ಬಳಸಿ. iOS ಬಳಕೆದಾರರು ಇಲ್ಲಿ ವೆಬ್‌ನಲ್ಲಿ ಚಂದಾದಾರರಾಗುತ್ತಾರೆ ಮತ್ತು ಬಿಲ್ಲಿಂಗ್ ನಿರ್ವಹಿಸುತ್ತಾರೆ.',
    heading: 'ಖಾತೆ',
    leadWithEmail: (email) => `${email} ಗಾಗಿ ಅಂಗಡಿ ಚಂದಾದಾರಿಕೆಗಳು, Razorpay ಚೆಕ್‌ಔಟ್, ಇನ್‌ವಾಯ್ಸ್‌ಗಳು, ರದ್ದುಗೊಳಿಸುವಿಕೆ ಮತ್ತು ಖಾತೆ ಪ್ರವೇಶವನ್ನು ನಿರ್ವಹಿಸಿ.`,
    accountFallback: 'ನಿಮ್ಮ Samaan-Bol ಖಾತೆ',
    linkedShops: 'ಲಿಂಕ್ ಮಾಡಿದ ಅಂಗಡಿಗಳು',
    loadingShops: 'ಅಂಗಡಿಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...',
    noShops: 'ಚಂದಾದಾರಿಕೆ API ಯಾವುದೇ ಅಂಗಡಿಗಳನ್ನು ಹಿಂತಿರುಗಿಸಲಿಲ್ಲ.',
    shopRoleFallback: 'ಅಂಗಡಿ ಪ್ರವೇಶ',
    statusLoading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ',
    statusActive: (interval) => `ಪ್ರೀಮಿಯಂ — ${interval}`,
    statusTrialEnds: (date) => `ಟ್ರಯಲ್ — ${date} ರಂದು ಮುಕ್ತಾಯ`,
    statusPastDue: 'ಪಾವತಿ ವಿಫಲವಾಗಿದೆ',
    statusCanceled: 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    statusLegacyFree: 'ಪರಂಪರೆ ಉಚಿತ',
    statusNone: 'ಸಕ್ರಿಯ ಚಂದಾದಾರಿಕೆ ಇಲ್ಲ',
    dateUnavailable: 'ಲಭ್ಯವಿಲ್ಲ',
    selectShop: 'ಒಂದು ಅಂಗಡಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    renewsOn: (date) => `${date} ರಂದು ನವೀಕರಣ ಅಥವಾ ಬದಲಾವಣೆ`,
    chooseIntervalPrompt: 'ಒಂದು ಬಿಲ್ಲಿಂಗ್ ಮಧ್ಯಂತರವನ್ನು ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ಈ ಅಂಗಡಿಗಾಗಿ Razorpay ಚೆಕ್‌ಔಟ್ ಪ್ರಾರಂಭಿಸಿ.',
    currentPlan: (label) => `ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಯೋಜನೆ ${label}. ಯೋಜನೆಗಳನ್ನು ಬದಲಾಯಿಸಲು ಅಥವಾ ಪಾವತಿ ವಿಧಾನವನ್ನು ನವೀಕರಿಸಲು Razorpay ನಲ್ಲಿ ಹೊಸ UPI ಆಟೋಪೇ ಮ್ಯಾಂಡೇಟ್ ಅನುಮೋದಿಸುವ ಅಗತ್ಯವಿದೆ.`,
    switchToAnnual: (amount) => `ವಾರ್ಷಿಕಕ್ಕೆ ಬದಲಾಯಿಸಿ — ${amount}`,
    switchToMonthly: (amount) => `ಮಾಸಿಕಕ್ಕೆ ಬದಲಾಯಿಸಿ — ${amount}`,
    updatePaymentMethod: 'ಪಾವತಿ ವಿಧಾನವನ್ನು ನವೀಕರಿಸಿ',
    cancelSubscription: 'ಚಂದಾದಾರಿಕೆಯನ್ನು ರದ್ದುಗೊಳಿಸಿ',
    subscribeWithAmount: (amount) => `ಚಂದಾದಾರಿಕೆ — ${amount}`,
    paymentHistory: 'ಪಾವತಿ ಇತಿಹಾಸ',
    invoiceDate: 'ದಿನಾಂಕ',
    invoiceAmount: 'ಮೊತ್ತ',
    invoiceStatus: 'ಸ್ಥಿತಿ',
    invoiceColumn: 'ಇನ್‌ವಾಯ್ಸ್',
    invoiceDownload: 'ಡೌನ್‌ಲೋಡ್',
    invoicePending: 'ಬಾಕಿ',
    invoicePaid: 'ಪಾವತಿಸಲಾಗಿದೆ',
    noInvoices: 'ಇನ್ನೂ ಯಾವುದೇ Razorpay ಇನ್‌ವಾಯ್ಸ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ.',
    backToPricing: 'ಬೆಲೆಗೆ ಹಿಂತಿರುಗಿ',
    errorRazorpayNotLoaded: 'Razorpay ಚೆಕ್‌ಔಟ್ ಇನ್ನೂ ಲೋಡ್ ಆಗಿಲ್ಲ. ಪುಟವನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    errorCheckoutMissingId: 'ಚೆಕ್‌ಔಟ್ ಪ್ರತಿಕ್ರಿಯೆಯಲ್ಲಿ subscription_id ಅಥವಾ key_id ಕಾಣುತ್ತಿಲ್ಲ.',
    errorLoadShops: 'ಅಂಗಡಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    errorLoadEntitlement: 'ಚಂದಾದಾರಿಕೆ ಸ್ಥಿತಿಯನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    errorStartCheckout: 'ಚೆಕ್‌ಔಟ್ ಪ್ರಾರಂಭಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    errorSwitchPlan: 'ಯೋಜನೆಯನ್ನು ಬದಲಾಯಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    errorPaymentMethod: 'ಪಾವತಿ ವಿಧಾನವನ್ನು ನವೀಕರಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    errorCancel: 'ಚಂದಾದಾರಿಕೆಯನ್ನು ರದ್ದುಗೊಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
  },
  contact: {
    heading: 'ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ',
    lead: 'ಚಂದಾದಾರಿಕೆ, ಇನ್‌ವಾಯ್ಸ್, ಖಾತೆ, ಮರುಪಾವತಿ ಅಥವಾ ಆಪ್ ಬೆಂಬಲಕ್ಕಾಗಿ, ಇಮೇಲ್ ಮೂಲಕ Samaan-Bol ತಂಡವನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    emailHeading: 'ಇಮೇಲ್',
    developerHeading: 'ಡೆವಲಪರ್ ಸಂಪರ್ಕ',
    responseHeading: 'ಪ್ರತಿಕ್ರಿಯೆ ಸಮಯ',
    responseBody: 'ನಾವು 2 ಕೆಲಸದ ದಿನಗಳಲ್ಲಿ ಪ್ರತಿಕ್ರಿಯಿಸಲು ಗುರಿಯನ್ನು ಹೊಂದಿದ್ದೇವೆ. ಮರುಪಾವತಿ ಮತ್ತು ಬಿಲ್ಲಿಂಗ್ ವಿನಂತಿಗಳಿಗೆ ಪರಿಶೀಲನೆಗಾಗಿ Razorpay ಪಾವತಿ ಗುರುತಿಸುವಿಕೆಗಳು ಬೇಕಾಗಬಹುದು.',
    businessHeading: 'ವ್ಯಾಪಾರ ವಿಳಾಸ',
    businessBody: 'Samaan-Bol, ಭಾರತ. Razorpay/GST ಇನ್‌ವಾಯ್ಸ್ ಅನುಸರಣೆಗಾಗಿ ದೃಢೀಕರಿಸಿದ ನಂತರ ನೋಂದಾಯಿತ ವ್ಯಾಪಾರ ವಿಳಾಸ ಮತ್ತು GSTIN ಅನ್ನು ಇಲ್ಲಿ ತೋರಿಸಲಾಗುತ್ತದೆ.',
  },
};

const gu: SubscriptionStrings = {
  brand: { tagline: 'ભારતીય રિટેલના હૃદય માટે બનાવેલ, વોઇસ-ફર્સ્ટ AI ઇન્વેન્ટરી મેનેજમેન્ટ.' },
  nav: { features: 'ફીચર્સ', ai: 'AI ઇન્ટેલિજન્સ', pricing: 'કિંમત', account: 'એકાઉન્ટ', download: 'એપ ડાઉનલોડ કરો' },
  footer: {
    product: 'પ્રોડક્ટ',
    company: 'કંપની',
    support: 'સહાય',
    features: 'ફીચર્સ',
    ai: 'AI ઇન્ટેલિજન્સ',
    pricing: 'કિંમત',
    about: 'અમારા વિશે',
    blog: 'બ્લોગ',
    careers: 'કારકિર્દી',
    contact: 'સંપર્ક',
    account: 'એકાઉન્ટ',
    refund: 'રિફંડ નીતિ',
    privacy: 'ગોપનીયતા નીતિ',
    terms: 'સેવા શરતો',
    copyright: '© Samaan-Bol. ભારતીય રિટેલ માટે વોઇસ-ફર્સ્ટ ઇન્વેન્ટરી.',
  },
  plans: { monthlyLabel: 'માસિક', annualLabel: 'વાર્ષિક', monthlyDescription: 'પ્રીમિયમ — માસિક', annualDescription: 'પ્રીમિયમ — વાર્ષિક' },
  pricing: {
    heroTitle: 'પ્રીમિયમ ₹499/મહિને અથવા ₹3,999/વર્ષે',
    heroLead:
      'સુરક્ષિત Razorpay UPI ઓટોપે માટે વેબ પર સબ્સ્ક્રાઇબ કરો. એપની બહાર બિલિંગ મેનેજ કરતા iOS વપરાશકર્તાઓ માટે બનાવેલ, અને એક જગ્યાએ ઇનવોઇસ, રદ્દ કરવા અને એકાઉન્ટ નિયંત્રણ ઇચ્છતા દરેક દુકાનદાર માટે ઉપયોગી.',
    ctaSubscribe: 'સબ્સ્ક્રાઇબ — સાઇન ઇન',
    ctaOpenInApp: 'એપમાં ખોલો',
    planSelectorLabel: 'પ્લાન પસંદગીકાર',
    billingIntervalLabel: 'બિલિંગ અંતરાલ',
    selectedPlan: 'પસંદ કરેલ પ્લાન',
    annualSavings: 'આશરે 33% બચાવો. અસરકારક કિંમત આશરે ₹333/મહિને.',
    monthlyFlexible: 'લવચીક માસિક બિલિંગ. આગામી બિલિંગ ચક્ર પહેલા રદ્દ કરો.',
    subscribeWithAmount: (amount) => `સબ્સ્ક્રાઇબ — ${amount}`,
    refundWindow: 'પ્રથમ ચાર્જથી 7-દિવસની રિફંડ વિન્ડો',
    razorpaySecure: 'Razorpay દ્વારા સુરક્ષિત ચૂકવણી',
    gstInvoice: 'Razorpay દ્વારા GST ઇનવોઇસ સહાય',
    comparisonHeading: 'તમારી દુકાન સાથે મેળ ખાતી ઇન્વેન્ટરી સિસ્ટમ પસંદ કરો',
    freeHeading: 'મફત',
    premiumHeading: 'પ્રીમિયમ',
    freeFeatures: ['મૂળભૂત ઉત્પાદન મેનેજમેન્ટ', 'એક દુકાન', 'મેન્યુઅલ સ્ટોક એન્ટ્રી', 'બારકોડ સ્કેન', 'ટીમ આમંત્રણો', 'આવશ્યક ઓડિટ ટ્રેલ'],
    premiumFeatures: [
      'હિન્દી, અંગ્રેજી અને પ્રાદેશિક ભારતીય ભાષાઓમાં વોઇસ AI',
      'AI સ્ટોક આગાહીઓ અને એક્સ્પાયરી ચેતવણીઓ',
      'એડવાન્સ્ડ એનાલિટિક્સ અને સંપૂર્ણ ઇન્વેન્ટરી ઇતિહાસ',
      'વધતા રિટેલર્સ માટે મલ્ટિ-શોપ સપોર્ટ',
      'સ્ટોકઆઉટ પહેલા AI ખરીદ-યાદી સૂચનો',
      'ઓડિટ ટ્રેલ સાથે ટીમ સહયોગ',
    ],
    secureBillingHeading: 'ભારતીય દુકાનો માટે સુરક્ષિત બિલિંગ',
    trustStrip: ['Razorpay હોસ્ટેડ ચેકઆઉટ', 'UPI ઓટોપે સપોર્ટેડ', 'ગમે ત્યારે રદ્દ કરો', '7-દિવસની રિફંડ વિન્ડો'],
    faqHeading: 'સબ્સ્ક્રાઇબ કરતા પહેલા પ્રશ્નો',
    faq: [
      { q: 'UPI ઓટોપે શું છે?', a: 'UPI ઓટોપે તમને એકવાર પુનરાવર્તિત મેન્ડેટ મંજૂર કરવા દે છે, પછી Razorpay RBI નિયમો હેઠળ ભવિષ્યના સબ્સ્ક્રિપ્શન પેમેન્ટ આપોઆપ એકત્રિત કરે છે.' },
      { q: 'શું હું ગમે ત્યારે રદ્દ કરી શકું?', a: 'હા. રદ્દ કરવાથી ભવિષ્યના નવીકરણ બંધ થાય છે. ચૂકવેલ સમયગાળાના અંત સુધી પ્રીમિયમ એક્સેસ ચાલુ રહે છે.' },
      { q: 'શું મને GST ઇનવોઇસ મળશે?', a: 'સબ્સ્ક્રિપ્શન માટે બિલિંગ માહિતી ઉપલબ્ધ હોય ત્યારે Razorpay દ્વારા ઇનવોઇસ જારી કરવામાં આવે છે.' },
      { q: 'શું મારી પેમેન્ટ માહિતી સુરક્ષિત છે?', a: 'Razorpay સંવેદનશીલ પેમેન્ટ વિગતો સંભાળે છે. Samaan-Bol માત્ર એક્સેસ મેનેજ કરવા માટે જરૂરી પેમેન્ટ અને સબ્સ્ક્રિપ્શન મેટાડેટા મેળવે છે.' },
    ],
  },
  account: {
    loadingSignIn: 'સાઇન-ઇન સ્થિતિ લોડ થઈ રહી છે...',
    loadingAccount: 'એકાઉન્ટ લોડ થઈ રહ્યું છે...',
    signedOutHeading: 'તમારા સબ્સ્ક્રિપ્શનને મેનેજ કરવા સાઇન ઇન કરો',
    signedOutLead: 'Samaan-Bol એપમાં તમે ઉપયોગ કરો છો તે જ Clerk એકાઉન્ટ ઇમેઇલનો ઉપયોગ કરો. iOS વપરાશકર્તાઓ અહીં વેબ પર સબ્સ્ક્રાઇબ કરે છે અને બિલિંગ મેનેજ કરે છે.',
    heading: 'એકાઉન્ટ',
    leadWithEmail: (email) => `${email} માટે દુકાન સબ્સ્ક્રિપ્શન, Razorpay ચેકઆઉટ, ઇનવોઇસ, રદ્દ કરવાં અને એકાઉન્ટ એક્સેસ મેનેજ કરો.`,
    accountFallback: 'તમારું Samaan-Bol એકાઉન્ટ',
    linkedShops: 'લિંક કરેલી દુકાનો',
    loadingShops: 'દુકાનો લોડ થઈ રહી છે...',
    noShops: 'સબ્સ્ક્રિપ્શન API એ કોઈ દુકાન પરત કરી નથી.',
    shopRoleFallback: 'દુકાન એક્સેસ',
    statusLoading: 'લોડ થઈ રહ્યું છે',
    statusActive: (interval) => `પ્રીમિયમ — ${interval}`,
    statusTrialEnds: (date) => `ટ્રાયલ — ${date} એ સમાપ્ત`,
    statusPastDue: 'પેમેન્ટ નિષ્ફળ',
    statusCanceled: 'રદ્દ',
    statusLegacyFree: 'લેગસી મફત',
    statusNone: 'કોઈ સક્રિય સબ્સ્ક્રિપ્શન નથી',
    dateUnavailable: 'ઉપલબ્ધ નથી',
    selectShop: 'એક દુકાન પસંદ કરો',
    renewsOn: (date) => `${date} એ નવીકરણ અથવા ફેરફાર`,
    chooseIntervalPrompt: 'એક બિલિંગ અંતરાલ પસંદ કરો અને આ દુકાન માટે Razorpay ચેકઆઉટ શરૂ કરો.',
    currentPlan: (label) => `તમારો વર્તમાન પ્લાન ${label} છે. પ્લાન બદલવા અથવા પેમેન્ટ પદ્ધતિ અપડેટ કરવા માટે Razorpay પર નવા UPI ઓટોપે મેન્ડેટ અધિકૃત કરવાની જરૂર છે.`,
    switchToAnnual: (amount) => `વાર્ષિક પર સ્વિચ કરો — ${amount}`,
    switchToMonthly: (amount) => `માસિક પર સ્વિચ કરો — ${amount}`,
    updatePaymentMethod: 'પેમેન્ટ પદ્ધતિ અપડેટ કરો',
    cancelSubscription: 'સબ્સ્ક્રિપ્શન રદ્દ કરો',
    subscribeWithAmount: (amount) => `સબ્સ્ક્રાઇબ — ${amount}`,
    paymentHistory: 'પેમેન્ટ ઇતિહાસ',
    invoiceDate: 'તારીખ',
    invoiceAmount: 'રકમ',
    invoiceStatus: 'સ્થિતિ',
    invoiceColumn: 'ઇનવોઇસ',
    invoiceDownload: 'ડાઉનલોડ',
    invoicePending: 'બાકી',
    invoicePaid: 'ચૂકવેલ',
    noInvoices: 'હજુ સુધી કોઈ Razorpay ઇનવોઇસ ઉપલબ્ધ નથી.',
    backToPricing: 'કિંમત પર પાછા',
    errorRazorpayNotLoaded: 'Razorpay ચેકઆઉટ હજુ સુધી લોડ થયું નથી. પેજ રિફ્રેશ કરો અને ફરી પ્રયાસ કરો.',
    errorCheckoutMissingId: 'ચેકઆઉટ પ્રતિસાદમાં subscription_id અથવા key_id ખૂટે છે.',
    errorLoadShops: 'દુકાનો લોડ કરવામાં અસમર્થ.',
    errorLoadEntitlement: 'સબ્સ્ક્રિપ્શન સ્થિતિ લોડ કરવામાં અસમર્થ.',
    errorStartCheckout: 'ચેકઆઉટ શરૂ કરવામાં અસમર્થ.',
    errorSwitchPlan: 'પ્લાન બદલવામાં અસમર્થ.',
    errorPaymentMethod: 'પેમેન્ટ પદ્ધતિ અપડેટ કરવામાં અસમર્થ.',
    errorCancel: 'સબ્સ્ક્રિપ્શન રદ્દ કરવામાં અસમર્થ.',
  },
  contact: {
    heading: 'સહાય સંપર્ક',
    lead: 'સબ્સ્ક્રિપ્શન, ઇનવોઇસ, એકાઉન્ટ, રિફંડ અથવા એપ સહાય માટે, ઇમેઇલ દ્વારા Samaan-Bol ટીમનો સંપર્ક કરો.',
    emailHeading: 'ઇમેઇલ',
    developerHeading: 'ડેવલપર સંપર્ક',
    responseHeading: 'પ્રતિસાદ સમય',
    responseBody: 'અમે 2 કાર્યકારી દિવસોમાં પ્રતિસાદ આપવાનું લક્ષ્ય રાખીએ છીએ. રિફંડ અને બિલિંગ વિનંતીઓ માટે ચકાસણી માટે Razorpay પેમેન્ટ ઓળખકર્તાઓની જરૂર પડી શકે છે.',
    businessHeading: 'વ્યવસાય સરનામું',
    businessBody: 'Samaan-Bol, ભારત. Razorpay/GST ઇનવોઇસ અનુપાલન માટે પુષ્ટિ થયા પછી નોંધાયેલ વ્યવસાય સરનામું અને GSTIN અહીં બતાવવામાં આવશે.',
  },
};

const ml: SubscriptionStrings = {
  brand: { tagline: 'ഇന്ത്യൻ റീട്ടെയിലിന്റെ ഹൃദയത്തിനായി നിർമ്മിച്ച, വോയ്സ്-ഫസ്റ്റ് AI ഇൻവെന്ററി മാനേജ്മെന്റ്.' },
  nav: { features: 'ഫീച്ചറുകൾ', ai: 'AI ഇന്റലിജൻസ്', pricing: 'വില', account: 'അക്കൗണ്ട്', download: 'ആപ്പ് ഡൗൺലോഡ് ചെയ്യുക' },
  footer: {
    product: 'ഉൽപ്പന്നം',
    company: 'കമ്പനി',
    support: 'പിന്തുണ',
    features: 'ഫീച്ചറുകൾ',
    ai: 'AI ഇന്റലിജൻസ്',
    pricing: 'വില',
    about: 'ഞങ്ങളെക്കുറിച്ച്',
    blog: 'ബ്ലോഗ്',
    careers: 'കരിയറുകൾ',
    contact: 'ബന്ധപ്പെടുക',
    account: 'അക്കൗണ്ട്',
    refund: 'റീഫണ്ട് നയം',
    privacy: 'സ്വകാര്യതാ നയം',
    terms: 'സേവന വ്യവസ്ഥകൾ',
    copyright: '© Samaan-Bol. ഇന്ത്യൻ റീട്ടെയിലിനായി വോയ്സ്-ഫസ്റ്റ് ഇൻവെന്ററി.',
  },
  plans: { monthlyLabel: 'പ്രതിമാസം', annualLabel: 'വാർഷികം', monthlyDescription: 'പ്രീമിയം — പ്രതിമാസം', annualDescription: 'പ്രീമിയം — വാർഷികം' },
  pricing: {
    heroTitle: 'പ്രീമിയം ₹499/മാസം അല്ലെങ്കിൽ ₹3,999/വർഷം',
    heroLead:
      'സുരക്ഷിതമായ Razorpay UPI ഓട്ടോപേയ്ക്ക് വെബിൽ സബ്സ്ക്രൈബ് ചെയ്യുക. ആപ്പിന് പുറത്ത് ബില്ലിംഗ് മാനേജ് ചെയ്യുന്ന iOS ഉപയോക്താക്കൾക്കായി നിർമ്മിച്ചത്, ഒപ്പം ഇൻവോയ്സുകൾ, റദ്ദാക്കലുകൾ, അക്കൗണ്ട് നിയന്ത്രണം എന്നിവ ഒരിടത്ത് ആഗ്രഹിക്കുന്ന ഏതൊരു കടയുടമയ്ക്കും ഉപയോഗപ്രദമാണ്.',
    ctaSubscribe: 'സബ്സ്ക്രൈബ് — സൈൻ ഇൻ',
    ctaOpenInApp: 'ആപ്പിൽ തുറക്കുക',
    planSelectorLabel: 'പ്ലാൻ സെലക്ടർ',
    billingIntervalLabel: 'ബില്ലിംഗ് ഇടവേള',
    selectedPlan: 'തിരഞ്ഞെടുത്ത പ്ലാൻ',
    annualSavings: 'ഏകദേശം 33% ലാഭിക്കുക. ഫലപ്രദമായ വില പ്രതിമാസം ഏകദേശം ₹333.',
    monthlyFlexible: 'വഴക്കമുള്ള പ്രതിമാസ ബില്ലിംഗ്. അടുത്ത ബില്ലിംഗ് ചക്രത്തിന് മുമ്പ് റദ്ദാക്കുക.',
    subscribeWithAmount: (amount) => `സബ്സ്ക്രൈബ് — ${amount}`,
    refundWindow: 'ആദ്യ ചാർജിൽ നിന്ന് 7-ദിവസത്തെ റീഫണ്ട് വിൻഡോ',
    razorpaySecure: 'Razorpay വഴി സുരക്ഷിതമായ പേയ്മെന്റുകൾ',
    gstInvoice: 'Razorpay വഴി GST ഇൻവോയ്സ് പിന്തുണ',
    comparisonHeading: 'നിങ്ങളുടെ കടയ്ക്ക് അനുയോജ്യമായ ഇൻവെന്ററി സിസ്റ്റം തിരഞ്ഞെടുക്കുക',
    freeHeading: 'സൗജന്യം',
    premiumHeading: 'പ്രീമിയം',
    freeFeatures: ['അടിസ്ഥാന ഉൽപ്പന്ന മാനേജ്മെന്റ്', 'ഒരു കട', 'മാനുവൽ സ്റ്റോക്ക് എൻട്രി', 'ബാർകോഡ് സ്കാൻ', 'ടീം ക്ഷണങ്ങൾ', 'അത്യാവശ്യ ഓഡിറ്റ് ട്രയിൽ'],
    premiumFeatures: [
      'ഹിന്ദി, ഇംഗ്ലീഷ്, പ്രാദേശിക ഇന്ത്യൻ ഭാഷകളിൽ വോയ്സ് AI',
      'AI സ്റ്റോക്ക് പ്രവചനങ്ങളും കാലഹരണ മുന്നറിയിപ്പുകളും',
      'വിപുലമായ വിശകലനവും പൂർണ്ണ ഇൻവെന്ററി ചരിത്രവും',
      'വളരുന്ന റീട്ടെയിലർമാർക്കായി മൾട്ടി-ഷോപ്പ് പിന്തുണ',
      'സ്റ്റോക്ക് തീരുന്നതിന് മുമ്പ് AI വാങ്ങൽ-ലിസ്റ്റ് നിർദ്ദേശങ്ങൾ',
      'ഓഡിറ്റ് ട്രയിലുകളോടെ ടീം സഹകരണം',
    ],
    secureBillingHeading: 'ഇന്ത്യൻ കടകൾക്കായി സുരക്ഷിതമായ ബില്ലിംഗ്',
    trustStrip: ['Razorpay ഹോസ്റ്റ് ചെയ്ത ചെക്കൗട്ട്', 'UPI ഓട്ടോപേ പിന്തുണ', 'എപ്പോൾ വേണമെങ്കിലും റദ്ദാക്കുക', '7-ദിവസത്തെ റീഫണ്ട് വിൻഡോ'],
    faqHeading: 'സബ്സ്ക്രൈബ് ചെയ്യുന്നതിന് മുമ്പുള്ള ചോദ്യങ്ങൾ',
    faq: [
      { q: 'UPI ഓട്ടോപേ എന്താണ്?', a: 'UPI ഓട്ടോപേ ഒരു തവണ ആവർത്തന മാൻഡേറ്റ് അംഗീകരിക്കാൻ നിങ്ങളെ അനുവദിക്കുന്നു, പിന്നീട് Razorpay RBI നിയമങ്ങൾക്ക് കീഴിൽ ഭാവി സബ്സ്ക്രിപ്ഷൻ പേയ്മെന്റുകൾ സ്വയം ശേഖരിക്കുന്നു.' },
      { q: 'ഞാൻ എപ്പോൾ വേണമെങ്കിലും റദ്ദാക്കാമോ?', a: 'അതെ. റദ്ദാക്കൽ ഭാവി പുതുക്കലുകൾ നിർത്തുന്നു. പണമടച്ച കാലയളവിന്റെ അവസാനം വരെ പ്രീമിയം ആക്സസ് തുടരും.' },
      { q: 'എനിക്ക് GST ഇൻവോയ്സ് ലഭിക്കുമോ?', a: 'സബ്സ്ക്രിപ്ഷനായി ബില്ലിംഗ് വിവരങ്ങൾ ലഭ്യമാകുമ്പോൾ Razorpay വഴി ഇൻവോയ്സുകൾ നൽകുന്നു.' },
      { q: 'എന്റെ പേയ്മെന്റ് വിവരങ്ങൾ സുരക്ഷിതമാണോ?', a: 'Razorpay സെൻസിറ്റീവ് പേയ്മെന്റ് വിശദാംശങ്ങൾ കൈകാര്യം ചെയ്യുന്നു. ആക്സസ് മാനേജ് ചെയ്യാൻ ആവശ്യമായ പേയ്മെന്റ്, സബ്സ്ക്രിപ്ഷൻ മെറ്റാഡാറ്റ മാത്രമേ Samaan-Bol-ന് ലഭിക്കൂ.' },
    ],
  },
  account: {
    loadingSignIn: 'സൈൻ-ഇൻ സ്റ്റാറ്റസ് ലോഡ് ചെയ്യുന്നു...',
    loadingAccount: 'അക്കൗണ്ട് ലോഡ് ചെയ്യുന്നു...',
    signedOutHeading: 'നിങ്ങളുടെ സബ്സ്ക്രിപ്ഷൻ മാനേജ് ചെയ്യാൻ സൈൻ ഇൻ ചെയ്യുക',
    signedOutLead: 'Samaan-Bol ആപ്പിൽ നിങ്ങൾ ഉപയോഗിക്കുന്ന അതേ Clerk അക്കൗണ്ട് ഇമെയിൽ ഉപയോഗിക്കുക. iOS ഉപയോക്താക്കൾ ഇവിടെ വെബിൽ സബ്സ്ക്രൈബ് ചെയ്യുകയും ബില്ലിംഗ് മാനേജ് ചെയ്യുകയും ചെയ്യുന്നു.',
    heading: 'അക്കൗണ്ട്',
    leadWithEmail: (email) => `${email}-നായി കട സബ്സ്ക്രിപ്ഷനുകൾ, Razorpay ചെക്കൗട്ട്, ഇൻവോയ്സുകൾ, റദ്ദാക്കലുകൾ, അക്കൗണ്ട് ആക്സസ് എന്നിവ മാനേജ് ചെയ്യുക.`,
    accountFallback: 'നിങ്ങളുടെ Samaan-Bol അക്കൗണ്ട്',
    linkedShops: 'ലിങ്ക് ചെയ്ത കടകൾ',
    loadingShops: 'കടകൾ ലോഡ് ചെയ്യുന്നു...',
    noShops: 'സബ്സ്ക്രിപ്ഷൻ API ഒരു കടയും തിരികെ നൽകിയില്ല.',
    shopRoleFallback: 'കട ആക്സസ്',
    statusLoading: 'ലോഡ് ചെയ്യുന്നു',
    statusActive: (interval) => `പ്രീമിയം — ${interval}`,
    statusTrialEnds: (date) => `ട്രയൽ — ${date}-ന് അവസാനിക്കും`,
    statusPastDue: 'പേയ്മെന്റ് പരാജയം',
    statusCanceled: 'റദ്ദാക്കി',
    statusLegacyFree: 'ലെഗസി സൗജന്യം',
    statusNone: 'സജീവ സബ്സ്ക്രിപ്ഷൻ ഇല്ല',
    dateUnavailable: 'ലഭ്യമല്ല',
    selectShop: 'ഒരു കട തിരഞ്ഞെടുക്കുക',
    renewsOn: (date) => `${date}-ന് പുതുക്കൽ അല്ലെങ്കിൽ മാറ്റം`,
    chooseIntervalPrompt: 'ഒരു ബില്ലിംഗ് ഇടവേള തിരഞ്ഞെടുത്ത് ഈ കടയ്ക്കായി Razorpay ചെക്കൗട്ട് ആരംഭിക്കുക.',
    currentPlan: (label) => `നിങ്ങളുടെ നിലവിലെ പ്ലാൻ ${label} ആണ്. പ്ലാനുകൾ മാറ്റാനോ പേയ്മെന്റ് രീതി അപ്ഡേറ്റ് ചെയ്യാനോ Razorpay-ൽ ഒരു പുതിയ UPI ഓട്ടോപേ മാൻഡേറ്റ് അംഗീകരിക്കേണ്ടതുണ്ട്.`,
    switchToAnnual: (amount) => `വാർഷികത്തിലേക്ക് മാറുക — ${amount}`,
    switchToMonthly: (amount) => `പ്രതിമാസത്തിലേക്ക് മാറുക — ${amount}`,
    updatePaymentMethod: 'പേയ്മെന്റ് രീതി അപ്ഡേറ്റ് ചെയ്യുക',
    cancelSubscription: 'സബ്സ്ക്രിപ്ഷൻ റദ്ദാക്കുക',
    subscribeWithAmount: (amount) => `സബ്സ്ക്രൈബ് — ${amount}`,
    paymentHistory: 'പേയ്മെന്റ് ചരിത്രം',
    invoiceDate: 'തീയതി',
    invoiceAmount: 'തുക',
    invoiceStatus: 'സ്റ്റാറ്റസ്',
    invoiceColumn: 'ഇൻവോയ്സ്',
    invoiceDownload: 'ഡൗൺലോഡ്',
    invoicePending: 'തീർപ്പുകൽപ്പിക്കാത്തത്',
    invoicePaid: 'അടച്ചു',
    noInvoices: 'ഇതുവരെ Razorpay ഇൻവോയ്സുകൾ ലഭ്യമല്ല.',
    backToPricing: 'വിലയിലേക്ക് മടങ്ങുക',
    errorRazorpayNotLoaded: 'Razorpay ചെക്കൗട്ട് ഇതുവരെ ലോഡ് ചെയ്തിട്ടില്ല. പേജ് റിഫ്രഷ് ചെയ്ത് വീണ്ടും ശ്രമിക്കുക.',
    errorCheckoutMissingId: 'ചെക്കൗട്ട് പ്രതികരണത്തിൽ subscription_id അല്ലെങ്കിൽ key_id ഇല്ല.',
    errorLoadShops: 'കടകൾ ലോഡ് ചെയ്യാൻ കഴിയില്ല.',
    errorLoadEntitlement: 'സബ്സ്ക്രിപ്ഷൻ സ്റ്റാറ്റസ് ലോഡ് ചെയ്യാൻ കഴിയില്ല.',
    errorStartCheckout: 'ചെക്കൗട്ട് ആരംഭിക്കാൻ കഴിയില്ല.',
    errorSwitchPlan: 'പ്ലാൻ മാറ്റാൻ കഴിയില്ല.',
    errorPaymentMethod: 'പേയ്മെന്റ് രീതി അപ്ഡേറ്റ് ചെയ്യാൻ കഴിയില്ല.',
    errorCancel: 'സബ്സ്ക്രിപ്ഷൻ റദ്ദാക്കാൻ കഴിയില്ല.',
  },
  contact: {
    heading: 'പിന്തുണാ ബന്ധപ്പെടൽ',
    lead: 'സബ്സ്ക്രിപ്ഷൻ, ഇൻവോയ്സ്, അക്കൗണ്ട്, റീഫണ്ട് അല്ലെങ്കിൽ ആപ്പ് പിന്തുണയ്ക്കായി, ഇമെയിൽ വഴി Samaan-Bol ടീമിനെ ബന്ധപ്പെടുക.',
    emailHeading: 'ഇമെയിൽ',
    developerHeading: 'ഡെവലപ്പർ ബന്ധപ്പെടൽ',
    responseHeading: 'പ്രതികരണ സമയം',
    responseBody: 'ഞങ്ങൾ 2 പ്രവൃത്തി ദിവസങ്ങൾക്കുള്ളിൽ പ്രതികരിക്കാൻ ലക്ഷ്യമിടുന്നു. റീഫണ്ടും ബില്ലിംഗ് അഭ്യർത്ഥനകൾക്കും സ്ഥിരീകരണത്തിനായി Razorpay പേയ്മെന്റ് ഐഡന്റിഫയറുകൾ ആവശ്യമായി വന്നേക്കാം.',
    businessHeading: 'ബിസിനസ് വിലാസം',
    businessBody: 'Samaan-Bol, ഇന്ത്യ. Razorpay/GST ഇൻവോയ്സ് അനുസരണത്തിനായി സ്ഥിരീകരിച്ച ശേഷം രജിസ്റ്റർ ചെയ്ത ബിസിനസ് വിലാസവും GSTIN-ഉം ഇവിടെ കാണിക്കും.',
  },
};

const pa: SubscriptionStrings = {
  brand: { tagline: 'ਭਾਰਤੀ ਰਿਟੇਲ ਦੇ ਦਿਲ ਲਈ ਬਣਾਇਆ ਗਿਆ, ਵੌਇਸ-ਫਸਟ AI ਇਨਵੈਂਟਰੀ ਪ੍ਰਬੰਧਨ।' },
  nav: { features: 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ', ai: 'AI ਇੰਟੈਲੀਜੈਂਸ', pricing: 'ਕੀਮਤ', account: 'ਖਾਤਾ', download: 'ਐਪ ਡਾਊਨਲੋਡ ਕਰੋ' },
  footer: {
    product: 'ਉਤਪਾਦ',
    company: 'ਕੰਪਨੀ',
    support: 'ਸਹਾਇਤਾ',
    features: 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    ai: 'AI ਇੰਟੈਲੀਜੈਂਸ',
    pricing: 'ਕੀਮਤ',
    about: 'ਸਾਡੇ ਬਾਰੇ',
    blog: 'ਬਲੌਗ',
    careers: 'ਕਰੀਅਰ',
    contact: 'ਸੰਪਰਕ',
    account: 'ਖਾਤਾ',
    refund: 'ਰਿਫੰਡ ਨੀਤੀ',
    privacy: 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
    terms: 'ਸੇਵਾ ਸ਼ਰਤਾਂ',
    copyright: '© Samaan-Bol. ਭਾਰਤੀ ਰਿਟੇਲ ਲਈ ਵੌਇਸ-ਫਸਟ ਇਨਵੈਂਟਰੀ।',
  },
  plans: { monthlyLabel: 'ਮਾਸਿਕ', annualLabel: 'ਸਾਲਾਨਾ', monthlyDescription: 'ਪ੍ਰੀਮੀਅਮ — ਮਾਸਿਕ', annualDescription: 'ਪ੍ਰੀਮੀਅਮ — ਸਾਲਾਨਾ' },
  pricing: {
    heroTitle: 'ਪ੍ਰੀਮੀਅਮ ₹499/ਮਹੀਨਾ ਜਾਂ ₹3,999/ਸਾਲ',
    heroLead:
      'ਸੁਰੱਖਿਅਤ Razorpay UPI ਆਟੋਪੇਅ ਲਈ ਵੈੱਬ ’ਤੇ ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ। ਐਪ ਤੋਂ ਬਾਹਰ ਬਿਲਿੰਗ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰਨ ਵਾਲੇ iOS ਉਪਭੋਗਤਾਵਾਂ ਲਈ ਬਣਾਇਆ ਗਿਆ, ਅਤੇ ਹਰ ਉਸ ਦੁਕਾਨਦਾਰ ਲਈ ਉਪਯੋਗੀ ਜੋ ਇੱਕ ਥਾਂ ’ਤੇ ਇਨਵੌਇਸ, ਰੱਦ ਕਰਨ ਅਤੇ ਖਾਤਾ ਨਿਯੰਤਰਣ ਚਾਹੁੰਦਾ ਹੈ।',
    ctaSubscribe: 'ਸਬਸਕ੍ਰਾਈਬ — ਸਾਈਨ ਇਨ',
    ctaOpenInApp: 'ਐਪ ਵਿੱਚ ਖੋਲ੍ਹੋ',
    planSelectorLabel: 'ਪਲਾਨ ਚੋਣਕਾਰ',
    billingIntervalLabel: 'ਬਿਲਿੰਗ ਅੰਤਰਾਲ',
    selectedPlan: 'ਚੁਣਿਆ ਗਿਆ ਪਲਾਨ',
    annualSavings: 'ਲਗਭਗ 33% ਬਚਾਓ। ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਕੀਮਤ ਲਗਭਗ ₹333/ਮਹੀਨਾ।',
    monthlyFlexible: 'ਲਚਕਦਾਰ ਮਾਸਿਕ ਬਿਲਿੰਗ। ਅਗਲੇ ਬਿਲਿੰਗ ਚੱਕਰ ਤੋਂ ਪਹਿਲਾਂ ਰੱਦ ਕਰੋ।',
    subscribeWithAmount: (amount) => `ਸਬਸਕ੍ਰਾਈਬ — ${amount}`,
    refundWindow: 'ਪਹਿਲੇ ਚਾਰਜ ਤੋਂ 7-ਦਿਨ ਦੀ ਰਿਫੰਡ ਵਿੰਡੋ',
    razorpaySecure: 'Razorpay ਰਾਹੀਂ ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ',
    gstInvoice: 'Razorpay ਰਾਹੀਂ GST ਇਨਵੌਇਸ ਸਹਾਇਤਾ',
    comparisonHeading: 'ਆਪਣੀ ਦੁਕਾਨ ਨਾਲ ਮੇਲ ਖਾਂਦੀ ਇਨਵੈਂਟਰੀ ਸਿਸਟਮ ਚੁਣੋ',
    freeHeading: 'ਮੁਫ਼ਤ',
    premiumHeading: 'ਪ੍ਰੀਮੀਅਮ',
    freeFeatures: ['ਮੁੱਢਲਾ ਉਤਪਾਦ ਪ੍ਰਬੰਧਨ', 'ਇੱਕ ਦੁਕਾਨ', 'ਮੈਨੂਅਲ ਸਟਾਕ ਐਂਟਰੀ', 'ਬਾਰਕੋਡ ਸਕੈਨ', 'ਟੀਮ ਸੱਦੇ', 'ਜ਼ਰੂਰੀ ਆਡਿਟ ਟ੍ਰੇਲ'],
    premiumFeatures: [
      'ਹਿੰਦੀ, ਅੰਗਰੇਜ਼ੀ ਅਤੇ ਖੇਤਰੀ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਵੌਇਸ AI',
      'AI ਸਟਾਕ ਭਵਿੱਖਬਾਣੀ ਅਤੇ ਮਿਆਦ ਦੇ ਅਲਰਟ',
      'ਉੱਨਤ ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਪੂਰਾ ਇਨਵੈਂਟਰੀ ਇਤਿਹਾਸ',
      'ਵਧ ਰਹੇ ਰਿਟੇਲਰਾਂ ਲਈ ਮਲਟੀ-ਸ਼ੌਪ ਸਪੋਰਟ',
      'ਸਟਾਕ ਖਤਮ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ AI ਖਰੀਦ-ਸੂਚੀ ਸੁਝਾਅ',
      'ਆਡਿਟ ਟ੍ਰੇਲ ਨਾਲ ਟੀਮ ਸਹਿਯੋਗ',
    ],
    secureBillingHeading: 'ਭਾਰਤੀ ਦੁਕਾਨਾਂ ਲਈ ਸੁਰੱਖਿਅਤ ਬਿਲਿੰਗ',
    trustStrip: ['Razorpay ਹੋਸਟਡ ਚੈੱਕਆਊਟ', 'UPI ਆਟੋਪੇਅ ਸਮਰਥਿਤ', 'ਕਦੇ ਵੀ ਰੱਦ ਕਰੋ', '7-ਦਿਨ ਦੀ ਰਿਫੰਡ ਵਿੰਡੋ'],
    faqHeading: 'ਸਬਸਕ੍ਰਾਈਬ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਸਵਾਲ',
    faq: [
      { q: 'UPI ਆਟੋਪੇਅ ਕੀ ਹੈ?', a: 'UPI ਆਟੋਪੇਅ ਤੁਹਾਨੂੰ ਇੱਕ ਵਾਰ ਆਵਰਤੀ ਮੈਂਡੇਟ ਨੂੰ ਮਨਜ਼ੂਰੀ ਦੇਣ ਦੀ ਆਗਿਆ ਦਿੰਦਾ ਹੈ, ਫਿਰ Razorpay RBI ਨਿਯਮਾਂ ਅਧੀਨ ਭਵਿੱਖ ਦੇ ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਭੁਗਤਾਨ ਆਟੋਮੈਟਿਕਲੀ ਇਕੱਠੇ ਕਰਦਾ ਹੈ।' },
      { q: 'ਕੀ ਮੈਂ ਕਦੇ ਵੀ ਰੱਦ ਕਰ ਸਕਦਾ ਹਾਂ?', a: 'ਹਾਂ। ਰੱਦ ਕਰਨਾ ਭਵਿੱਖ ਦੇ ਨਵੀਨੀਕਰਨ ਨੂੰ ਰੋਕਦਾ ਹੈ। ਪ੍ਰੀਮੀਅਮ ਪਹੁੰਚ ਅਦਾ ਕੀਤੀ ਮਿਆਦ ਦੇ ਅੰਤ ਤੱਕ ਜਾਰੀ ਰਹਿੰਦੀ ਹੈ।' },
      { q: 'ਕੀ ਮੈਨੂੰ GST ਇਨਵੌਇਸ ਮਿਲੇਗਾ?', a: 'ਜਦੋਂ ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਲਈ ਬਿਲਿੰਗ ਜਾਣਕਾਰੀ ਉਪਲਬਧ ਹੁੰਦੀ ਹੈ ਤਾਂ Razorpay ਰਾਹੀਂ ਇਨਵੌਇਸ ਜਾਰੀ ਕੀਤੇ ਜਾਂਦੇ ਹਨ।' },
      { q: 'ਕੀ ਮੇਰੀ ਭੁਗਤਾਨ ਜਾਣਕਾਰੀ ਸੁਰੱਖਿਅਤ ਹੈ?', a: 'Razorpay ਸੰਵੇਦਨਸ਼ੀਲ ਭੁਗਤਾਨ ਵੇਰਵਿਆਂ ਨੂੰ ਸੰਭਾਲਦਾ ਹੈ। Samaan-Bol ਪਹੁੰਚ ਪ੍ਰਬੰਧਨ ਲਈ ਲੋੜੀਂਦਾ ਭੁਗਤਾਨ ਅਤੇ ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਮੈਟਾਡੇਟਾ ਹੀ ਪ੍ਰਾਪਤ ਕਰਦਾ ਹੈ।' },
    ],
  },
  account: {
    loadingSignIn: 'ਸਾਈਨ-ਇਨ ਸਥਿਤੀ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...',
    loadingAccount: 'ਖਾਤਾ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    signedOutHeading: 'ਆਪਣੀ ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰਨ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ',
    signedOutLead: 'Samaan-Bol ਐਪ ਵਿੱਚ ਤੁਸੀਂ ਜੋ ਉਹੀ Clerk ਖਾਤਾ ਈਮੇਲ ਵਰਤਦੇ ਹੋ ਉਸ ਨੂੰ ਵਰਤੋ। iOS ਉਪਭੋਗਤਾ ਇੱਥੇ ਵੈੱਬ ’ਤੇ ਸਬਸਕ੍ਰਾਈਬ ਕਰਦੇ ਹਨ ਅਤੇ ਬਿਲਿੰਗ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰਦੇ ਹਨ।',
    heading: 'ਖਾਤਾ',
    leadWithEmail: (email) => `${email} ਲਈ ਦੁਕਾਨ ਸਬਸਕ੍ਰਿਪਸ਼ਨ, Razorpay ਚੈੱਕਆਊਟ, ਇਨਵੌਇਸ, ਰੱਦ ਅਤੇ ਖਾਤਾ ਪਹੁੰਚ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ।`,
    accountFallback: 'ਤੁਹਾਡਾ Samaan-Bol ਖਾਤਾ',
    linkedShops: 'ਲਿੰਕਡ ਦੁਕਾਨਾਂ',
    loadingShops: 'ਦੁਕਾਨਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ...',
    noShops: 'ਸਬਸਕ੍ਰਿਪਸ਼ਨ API ਨੇ ਕੋਈ ਦੁਕਾਨ ਵਾਪਸ ਨਹੀਂ ਕੀਤੀ।',
    shopRoleFallback: 'ਦੁਕਾਨ ਪਹੁੰਚ',
    statusLoading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ',
    statusActive: (interval) => `ਪ੍ਰੀਮੀਅਮ — ${interval}`,
    statusTrialEnds: (date) => `ਟ੍ਰਾਇਲ — ${date} ਨੂੰ ਖਤਮ`,
    statusPastDue: 'ਭੁਗਤਾਨ ਅਸਫਲ',
    statusCanceled: 'ਰੱਦ',
    statusLegacyFree: 'ਲੀਗੇਸੀ ਮੁਫ਼ਤ',
    statusNone: 'ਕੋਈ ਸਰਗਰਮ ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਨਹੀਂ',
    dateUnavailable: 'ਉਪਲਬਧ ਨਹੀਂ',
    selectShop: 'ਇੱਕ ਦੁਕਾਨ ਚੁਣੋ',
    renewsOn: (date) => `${date} ਨੂੰ ਨਵੀਨੀਕਰਨ ਜਾਂ ਬਦਲਾਅ`,
    chooseIntervalPrompt: 'ਇੱਕ ਬਿਲਿੰਗ ਅੰਤਰਾਲ ਚੁਣੋ ਅਤੇ ਇਸ ਦੁਕਾਨ ਲਈ Razorpay ਚੈੱਕਆਊਟ ਸ਼ੁਰੂ ਕਰੋ।',
    currentPlan: (label) => `ਤੁਹਾਡਾ ਮੌਜੂਦਾ ਪਲਾਨ ${label} ਹੈ। ਪਲਾਨ ਬਦਲਣ ਜਾਂ ਭੁਗਤਾਨ ਵਿਧੀ ਨੂੰ ਅੱਪਡੇਟ ਕਰਨ ਲਈ Razorpay ’ਤੇ ਇੱਕ ਨਵਾਂ UPI ਆਟੋਪੇਅ ਮੈਂਡੇਟ ਪ੍ਰਮਾਣਿਤ ਕਰਨਾ ਜ਼ਰੂਰੀ ਹੈ।`,
    switchToAnnual: (amount) => `ਸਾਲਾਨਾ ’ਤੇ ਸਵਿਚ ਕਰੋ — ${amount}`,
    switchToMonthly: (amount) => `ਮਾਸਿਕ ’ਤੇ ਸਵਿਚ ਕਰੋ — ${amount}`,
    updatePaymentMethod: 'ਭੁਗਤਾਨ ਵਿਧੀ ਅੱਪਡੇਟ ਕਰੋ',
    cancelSubscription: 'ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਰੱਦ ਕਰੋ',
    subscribeWithAmount: (amount) => `ਸਬਸਕ੍ਰਾਈਬ — ${amount}`,
    paymentHistory: 'ਭੁਗਤਾਨ ਇਤਿਹਾਸ',
    invoiceDate: 'ਮਿਤੀ',
    invoiceAmount: 'ਰਕਮ',
    invoiceStatus: 'ਸਥਿਤੀ',
    invoiceColumn: 'ਇਨਵੌਇਸ',
    invoiceDownload: 'ਡਾਊਨਲੋਡ',
    invoicePending: 'ਬਕਾਇਆ',
    invoicePaid: 'ਅਦਾ ਕੀਤਾ',
    noInvoices: 'ਅਜੇ ਤੱਕ ਕੋਈ Razorpay ਇਨਵੌਇਸ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
    backToPricing: 'ਕੀਮਤ ’ਤੇ ਵਾਪਸ',
    errorRazorpayNotLoaded: 'Razorpay ਚੈੱਕਆਊਟ ਅਜੇ ਲੋਡ ਨਹੀਂ ਹੋਇਆ ਹੈ। ਪੇਜ ਨੂੰ ਰਿਫਰੈਸ਼ ਕਰੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    errorCheckoutMissingId: 'ਚੈੱਕਆਊਟ ਜਵਾਬ ਵਿੱਚ subscription_id ਜਾਂ key_id ਗੁੰਮ ਹੈ।',
    errorLoadShops: 'ਦੁਕਾਨਾਂ ਲੋਡ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ।',
    errorLoadEntitlement: 'ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਸਥਿਤੀ ਲੋਡ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ।',
    errorStartCheckout: 'ਚੈੱਕਆਊਟ ਸ਼ੁਰੂ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ।',
    errorSwitchPlan: 'ਪਲਾਨ ਬਦਲਣ ਵਿੱਚ ਅਸਮਰੱਥ।',
    errorPaymentMethod: 'ਭੁਗਤਾਨ ਵਿਧੀ ਅੱਪਡੇਟ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ।',
    errorCancel: 'ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਰੱਦ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ।',
  },
  contact: {
    heading: 'ਸਹਾਇਤਾ ਸੰਪਰਕ',
    lead: 'ਸਬਸਕ੍ਰਿਪਸ਼ਨ, ਇਨਵੌਇਸ, ਖਾਤਾ, ਰਿਫੰਡ ਜਾਂ ਐਪ ਸਹਾਇਤਾ ਲਈ, ਈਮੇਲ ਰਾਹੀਂ Samaan-Bol ਟੀਮ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।',
    emailHeading: 'ਈਮੇਲ',
    developerHeading: 'ਡਿਵੈਲਪਰ ਸੰਪਰਕ',
    responseHeading: 'ਜਵਾਬ ਸਮਾਂ',
    responseBody: 'ਅਸੀਂ 2 ਕੰਮ ਕਾਜ ਦੇ ਦਿਨਾਂ ਅੰਦਰ ਜਵਾਬ ਦੇਣ ਦਾ ਟੀਚਾ ਰੱਖਦੇ ਹਾਂ। ਰਿਫੰਡ ਅਤੇ ਬਿਲਿੰਗ ਬੇਨਤੀਆਂ ਲਈ ਤਸਦੀਕ ਲਈ Razorpay ਭੁਗਤਾਨ ਪਛਾਣਕਰਤਾਵਾਂ ਦੀ ਲੋੜ ਹੋ ਸਕਦੀ ਹੈ।',
    businessHeading: 'ਕਾਰੋਬਾਰੀ ਪਤਾ',
    businessBody: 'Samaan-Bol, ਭਾਰਤ। Razorpay/GST ਇਨਵੌਇਸ ਪਾਲਣਾ ਲਈ ਪੁਸ਼ਟੀ ਹੋਣ ਤੋਂ ਬਾਅਦ ਰਜਿਸਟਰਡ ਕਾਰੋਬਾਰੀ ਪਤਾ ਅਤੇ GSTIN ਇੱਥੇ ਦਿਖਾਇਆ ਜਾਵੇਗਾ।',
  },
};

const or: SubscriptionStrings = {
  brand: { tagline: 'ଭାରତୀୟ ଖୁଚୁରା ବ୍ୟବସାୟର ହୃଦୟ ପାଇଁ ତିଆରି, ଭଏସ୍-ଫାର୍ଷ୍ଟ AI ଇନଭେଣ୍ଟରୀ ପରିଚାଳନା।' },
  nav: { features: 'ବିଶେଷତା', ai: 'AI ଇଣ୍ଟେଲିଜେନ୍ସ', pricing: 'ମୂଲ୍ୟ', account: 'ଆକାଉଣ୍ଟ', download: 'ଆପ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ' },
  footer: {
    product: 'ଉତ୍ପାଦ',
    company: 'କମ୍ପାନୀ',
    support: 'ସମର୍ଥନ',
    features: 'ବିଶେଷତା',
    ai: 'AI ଇଣ୍ଟେଲିଜେନ୍ସ',
    pricing: 'ମୂଲ୍ୟ',
    about: 'ଆମ ବିଷୟରେ',
    blog: 'ବ୍ଲଗ୍',
    careers: 'କ୍ୟାରିୟର୍',
    contact: 'ଯୋଗାଯୋଗ',
    account: 'ଆକାଉଣ୍ଟ',
    refund: 'ରିଫଣ୍ଡ ନୀତି',
    privacy: 'ଗୋପନୀୟତା ନୀତି',
    terms: 'ସେବା ସର୍ତ୍ତାବଳୀ',
    copyright: '© Samaan-Bol. ଭାରତୀୟ ଖୁଚୁରା ବ୍ୟବସାୟ ପାଇଁ ଭଏସ୍-ଫାର୍ଷ୍ଟ ଇନଭେଣ୍ଟରୀ।',
  },
  plans: { monthlyLabel: 'ମାସିକ', annualLabel: 'ବାର୍ଷିକ', monthlyDescription: 'ପ୍ରିମିୟମ୍ — ମାସିକ', annualDescription: 'ପ୍ରିମିୟମ୍ — ବାର୍ଷିକ' },
  pricing: {
    heroTitle: 'ପ୍ରିମିୟମ୍ ₹499/ମାସ କିମ୍ବା ₹3,999/ବର୍ଷ',
    heroLead:
      'ସୁରକ୍ଷିତ Razorpay UPI ଅଟୋପେ ପାଇଁ ୱେବରେ ସବସ୍କ୍ରାଇବ କରନ୍ତୁ। ଆପ୍ ବାହାରେ ବିଲିଂ ପରିଚାଳନା କରୁଥିବା iOS ଉପଯୋଗକର୍ତ୍ତାଙ୍କ ପାଇଁ ତିଆରି, ଏବଂ ଗୋଟିଏ ଜାଗାରେ ଇନଭଏସ୍, ବାତିଲ ଏବଂ ଆକାଉଣ୍ଟ ନିୟନ୍ତ୍ରଣ ଚାହୁଁଥିବା ପ୍ରତ୍ୟେକ ଦୋକାନୀଙ୍କ ପାଇଁ ଉପଯୋଗୀ।',
    ctaSubscribe: 'ସବସ୍କ୍ରାଇବ — ସାଇନ୍ ଇନ୍',
    ctaOpenInApp: 'ଆପ୍ ରେ ଖୋଲନ୍ତୁ',
    planSelectorLabel: 'ପ୍ଲାନ୍ ବାଛନ୍ତୁ',
    billingIntervalLabel: 'ବିଲିଂ ବ୍ୟବଧାନ',
    selectedPlan: 'ବଛାଯାଇଥିବା ପ୍ଲାନ୍',
    annualSavings: 'ପ୍ରାୟ 33% ସଞ୍ଚୟ କରନ୍ତୁ। ପ୍ରଭାବୀ ମୂଲ୍ୟ ପ୍ରାୟ ₹333/ମାସ।',
    monthlyFlexible: 'ନମନୀୟ ମାସିକ ବିଲିଂ। ପରବର୍ତ୍ତୀ ବିଲିଂ ଚକ୍ର ପୂର୍ବରୁ ବାତିଲ କରନ୍ତୁ।',
    subscribeWithAmount: (amount) => `ସବସ୍କ୍ରାଇବ — ${amount}`,
    refundWindow: 'ପ୍ରଥମ ଚାର୍ଜରୁ 7-ଦିନର ରିଫଣ୍ଡ ୱିଣ୍ଡୋ',
    razorpaySecure: 'Razorpay ମାଧ୍ୟମରେ ସୁରକ୍ଷିତ ପେମେଣ୍ଟ',
    gstInvoice: 'Razorpay ମାଧ୍ୟମରେ GST ଇନଭଏସ୍ ସମର୍ଥନ',
    comparisonHeading: 'ଆପଣଙ୍କ ଦୋକାନ ସହିତ ମେଳ ଖାଉଥିବା ଇନଭେଣ୍ଟରୀ ସିଷ୍ଟମ୍ ବାଛନ୍ତୁ',
    freeHeading: 'ମାଗଣା',
    premiumHeading: 'ପ୍ରିମିୟମ୍',
    freeFeatures: ['ମୂଳ ଉତ୍ପାଦ ପରିଚାଳନା', 'ଗୋଟିଏ ଦୋକାନ', 'ମାନୁଆଲ ଷ୍ଟକ୍ ଏଣ୍ଟ୍ରି', 'ବାରକୋଡ୍ ସ୍କାନ୍', 'ଟିମ୍ ଆମନ୍ତ୍ରଣ', 'ଆବଶ୍ୟକ ଅଡିଟ୍ ଟ୍ରେଲ୍'],
    premiumFeatures: [
      'ହିନ୍ଦୀ, ଇଂରାଜୀ ଏବଂ ଆଞ୍ଚଳିକ ଭାରତୀୟ ଭାଷାରେ ଭଏସ୍ AI',
      'AI ଷ୍ଟକ୍ ପୂର୍ବାନୁମାନ ଏବଂ ମିଆଦ ଶେଷ ସତର୍କତା',
      'ଉନ୍ନତ ବିଶ୍ଳେଷଣ ଏବଂ ସମ୍ପୂର୍ଣ୍ଣ ଇନଭେଣ୍ଟରୀ ଇତିହାସ',
      'ବଢୁଥିବା ଖୁଚୁରା ବ୍ୟବସାୟୀଙ୍କ ପାଇଁ ମଲ୍ଟି-ଶପ୍ ସମର୍ଥନ',
      'ଷ୍ଟକ୍ ଶେଷ ହେବା ପୂର୍ବରୁ AI କିଣ-ତାଲିକା ପରାମର୍ଶ',
      'ଅଡିଟ୍ ଟ୍ରେଲ୍ ସହିତ ଟିମ୍ ସହଯୋଗ',
    ],
    secureBillingHeading: 'ଭାରତୀୟ ଦୋକାନଗୁଡ଼ିକ ପାଇଁ ସୁରକ୍ଷିତ ବିଲିଂ',
    trustStrip: ['Razorpay ହୋଷ୍ଟ କରାଯାଇଥିବା ଚେକଆଉଟ୍', 'UPI ଅଟୋପେ ସମର୍ଥିତ', 'ଯେକୌଣସି ସମୟରେ ବାତିଲ କରନ୍ତୁ', '7-ଦିନର ରିଫଣ୍ଡ ୱିଣ୍ଡୋ'],
    faqHeading: 'ସବସ୍କ୍ରାଇବ କରିବା ପୂର୍ବରୁ ପ୍ରଶ୍ନ',
    faq: [
      { q: 'UPI ଅଟୋପେ କ\'ଣ?', a: 'UPI ଅଟୋପେ ଆପଣଙ୍କୁ ଥରେ ପୁନରାବୃତ୍ତି ମ୍ୟାଣ୍ଡେଟ୍ ଅନୁମୋଦନ କରିବାକୁ ଅନୁମତି ଦିଏ, ତା\'ପରେ Razorpay RBI ନିୟମ ଅଧୀନରେ ସ୍ୱୟଂଚାଳିତ ଭାବେ ଭବିଷ୍ୟତର ସବସ୍କ୍ରିପ୍ସନ୍ ପେମେଣ୍ଟ ସଂଗ୍ରହ କରେ।' },
      { q: 'ମୁଁ ଯେକୌଣସି ସମୟରେ ବାତିଲ କରିପାରିବି କି?', a: 'ହଁ। ବାତିଲ ଭବିଷ୍ୟତର ନବୀକରଣକୁ ଅଟକାଇଥାଏ। ପ୍ରିମିୟମ୍ ପ୍ରବେଶ ପ୍ରଦତ୍ତ ଅବଧି ଶେଷ ପର୍ଯ୍ୟନ୍ତ ଜାରି ରହିଥାଏ।' },
      { q: 'ମୁଁ କ\'ଣ GST ଇନଭଏସ୍ ପାଇବି?', a: 'ସବସ୍କ୍ରିପ୍ସନ୍ ପାଇଁ ବିଲିଂ ସୂଚନା ଉପଲବ୍ଧ ଥିଲେ Razorpay ମାଧ୍ୟମରେ ଇନଭଏସ୍ ଜାରି କରାଯାଏ।' },
      { q: 'ମୋର ପେମେଣ୍ଟ ସୂଚନା ସୁରକ୍ଷିତ କି?', a: 'Razorpay ସମ୍ବେଦନଶୀଳ ପେମେଣ୍ଟ ବିବରଣୀ ପରିଚାଳନା କରେ। Samaan-Bol କେବଳ ପ୍ରବେଶ ପରିଚାଳନା ପାଇଁ ଆବଶ୍ୟକ ପେମେଣ୍ଟ ଏବଂ ସବସ୍କ୍ରିପ୍ସନ୍ ମେଟାଡାଟା ଗ୍ରହଣ କରେ।' },
    ],
  },
  account: {
    loadingSignIn: 'ସାଇନ-ଇନ ସ୍ଥିତି ଲୋଡ୍ ହେଉଛି...',
    loadingAccount: 'ଆକାଉଣ୍ଟ ଲୋଡ୍ ହେଉଛି...',
    signedOutHeading: 'ଆପଣଙ୍କ ସବସ୍କ୍ରିପ୍ସନ୍ ପରିଚାଳନା କରିବାକୁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    signedOutLead: 'Samaan-Bol ଆପରେ ଆପଣ ବ୍ୟବହାର କରୁଥିବା ସେହି ସମାନ Clerk ଆକାଉଣ୍ଟ ଇମେଲ ବ୍ୟବହାର କରନ୍ତୁ। iOS ଉପଯୋଗକର୍ତ୍ତା ଏଠାରେ ୱେବରେ ସବସ୍କ୍ରାଇବ କରନ୍ତି ଏବଂ ବିଲିଂ ପରିଚାଳନା କରନ୍ତି।',
    heading: 'ଆକାଉଣ୍ଟ',
    leadWithEmail: (email) => `${email} ପାଇଁ ଦୋକାନ ସବସ୍କ୍ରିପ୍ସନ୍, Razorpay ଚେକଆଉଟ୍, ଇନଭଏସ୍, ବାତିଲ ଏବଂ ଆକାଉଣ୍ଟ ପ୍ରବେଶ ପରିଚାଳନା କରନ୍ତୁ।`,
    accountFallback: 'ଆପଣଙ୍କ Samaan-Bol ଆକାଉଣ୍ଟ',
    linkedShops: 'ଲିଙ୍କ୍ କରାଯାଇଥିବା ଦୋକାନ',
    loadingShops: 'ଦୋକାନଗୁଡ଼ିକ ଲୋଡ୍ ହେଉଛି...',
    noShops: 'ସବସ୍କ୍ରିପ୍ସନ୍ API କୌଣସି ଦୋକାନ ଫେରସ୍ତ କରିନାହିଁ।',
    shopRoleFallback: 'ଦୋକାନ ପ୍ରବେଶ',
    statusLoading: 'ଲୋଡ୍ ହେଉଛି',
    statusActive: (interval) => `ପ୍ରିମିୟମ୍ — ${interval}`,
    statusTrialEnds: (date) => `ଟ୍ରାଏଲ୍ — ${date} ରେ ଶେଷ`,
    statusPastDue: 'ପେମେଣ୍ଟ ବିଫଳ',
    statusCanceled: 'ବାତିଲ',
    statusLegacyFree: 'ଲେଗାସୀ ମାଗଣା',
    statusNone: 'କୌଣସି ସକ୍ରିୟ ସବସ୍କ୍ରିପ୍ସନ୍ ନାହିଁ',
    dateUnavailable: 'ଉପଲବ୍ଧ ନାହିଁ',
    selectShop: 'ଗୋଟିଏ ଦୋକାନ ବାଛନ୍ତୁ',
    renewsOn: (date) => `${date} ରେ ନବୀକରଣ କିମ୍ବା ପରିବର୍ତ୍ତନ`,
    chooseIntervalPrompt: 'ଗୋଟିଏ ବିଲିଂ ବ୍ୟବଧାନ ବାଛନ୍ତୁ ଏବଂ ଏହି ଦୋକାନ ପାଇଁ Razorpay ଚେକଆଉଟ୍ ଆରମ୍ଭ କରନ୍ତୁ।',
    currentPlan: (label) => `ଆପଣଙ୍କ ବର୍ତ୍ତମାନର ପ୍ଲାନ୍ ${label} ଅଟେ। ପ୍ଲାନ୍ ବଦଳାଇବାକୁ କିମ୍ବା ପେମେଣ୍ଟ ପଦ୍ଧତି ଅଦ୍ୟତନ କରିବାକୁ Razorpay ରେ ଏକ ନୂଆ UPI ଅଟୋପେ ମ୍ୟାଣ୍ଡେଟ୍ ଅନୁମୋଦନ କରିବା ଆବଶ୍ୟକ।`,
    switchToAnnual: (amount) => `ବାର୍ଷିକକୁ ସ୍ୱିଚ୍ କରନ୍ତୁ — ${amount}`,
    switchToMonthly: (amount) => `ମାସିକକୁ ସ୍ୱିଚ୍ କରନ୍ତୁ — ${amount}`,
    updatePaymentMethod: 'ପେମେଣ୍ଟ ପଦ୍ଧତି ଅଦ୍ୟତନ କରନ୍ତୁ',
    cancelSubscription: 'ସବସ୍କ୍ରିପ୍ସନ୍ ବାତିଲ କରନ୍ତୁ',
    subscribeWithAmount: (amount) => `ସବସ୍କ୍ରାଇବ — ${amount}`,
    paymentHistory: 'ପେମେଣ୍ଟ ଇତିହାସ',
    invoiceDate: 'ତାରିଖ',
    invoiceAmount: 'ରାଶି',
    invoiceStatus: 'ସ୍ଥିତି',
    invoiceColumn: 'ଇନଭଏସ୍',
    invoiceDownload: 'ଡାଉନଲୋଡ୍',
    invoicePending: 'ବକୟା',
    invoicePaid: 'ଦେୟ ହୋଇଛି',
    noInvoices: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି Razorpay ଇନଭଏସ୍ ଉପଲବ୍ଧ ନାହିଁ।',
    backToPricing: 'ମୂଲ୍ୟକୁ ଫେରନ୍ତୁ',
    errorRazorpayNotLoaded: 'Razorpay ଚେକଆଉଟ୍ ଏପର୍ଯ୍ୟନ୍ତ ଲୋଡ୍ ହୋଇନାହିଁ। ପୃଷ୍ଠାକୁ ରିଫ୍ରେସ୍ କରନ୍ତୁ ଏବଂ ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',
    errorCheckoutMissingId: 'ଚେକଆଉଟ୍ ପ୍ରତିକ୍ରିୟାରେ subscription_id କିମ୍ବା key_id ନାହିଁ।',
    errorLoadShops: 'ଦୋକାନଗୁଡ଼ିକ ଲୋଡ୍ କରିବାକୁ ଅସମର୍ଥ।',
    errorLoadEntitlement: 'ସବସ୍କ୍ରିପ୍ସନ୍ ସ୍ଥିତି ଲୋଡ୍ କରିବାକୁ ଅସମର୍ଥ।',
    errorStartCheckout: 'ଚେକଆଉଟ୍ ଆରମ୍ଭ କରିବାକୁ ଅସମର୍ଥ।',
    errorSwitchPlan: 'ପ୍ଲାନ୍ ବଦଳାଇବାକୁ ଅସମର୍ଥ।',
    errorPaymentMethod: 'ପେମେଣ୍ଟ ପଦ୍ଧତି ଅଦ୍ୟତନ କରିବାକୁ ଅସମର୍ଥ।',
    errorCancel: 'ସବସ୍କ୍ରିପ୍ସନ୍ ବାତିଲ କରିବାକୁ ଅସମର୍ଥ।',
  },
  contact: {
    heading: 'ସମର୍ଥନ ଯୋଗାଯୋଗ',
    lead: 'ସବସ୍କ୍ରିପ୍ସନ୍, ଇନଭଏସ୍, ଆକାଉଣ୍ଟ, ରିଫଣ୍ଡ କିମ୍ବା ଆପ୍ ସମର୍ଥନ ପାଇଁ, ଇମେଲ ମାଧ୍ୟମରେ Samaan-Bol ଟିମ୍ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ।',
    emailHeading: 'ଇମେଲ',
    developerHeading: 'ଡେଭଲପର୍ ଯୋଗାଯୋଗ',
    responseHeading: 'ପ୍ରତିକ୍ରିୟା ସମୟ',
    responseBody: 'ଆମେ 2 କାର୍ଯ୍ୟ ଦିବସ ମଧ୍ୟରେ ପ୍ରତିକ୍ରିୟା ଦେବାକୁ ଲକ୍ଷ୍ୟ ରଖୁଛୁ। ରିଫଣ୍ଡ ଏବଂ ବିଲିଂ ଅନୁରୋଧ ପାଇଁ ସତ୍ୟାପନ ପାଇଁ Razorpay ପେମେଣ୍ଟ ଚିହ୍ନଟକାରୀ ଆବଶ୍ୟକ ହୋଇପାରେ।',
    businessHeading: 'ବ୍ୟବସାୟ ଠିକଣା',
    businessBody: 'Samaan-Bol, ଭାରତ। Razorpay/GST ଇନଭଏସ୍ ଅନୁପାଳନ ପାଇଁ ନିଶ୍ଚିତ ହେବା ପରେ ପଞ୍ଜିକୃତ ବ୍ୟବସାୟ ଠିକଣା ଏବଂ GSTIN ଏଠାରେ ଦେଖାଯିବ।',
  },
};

export const subscriptionStrings: Record<Locale, SubscriptionStrings> = {
  en,
  hi,
  bn,
  ta,
  te,
  mr,
  kn,
  gu,
  ml,
  pa,
  or,
};

export function getSubscriptionStrings(locale: Locale): SubscriptionStrings {
  return subscriptionStrings[locale] ?? en;
}
